/* Stage 2F independent assertions. Uses real sim/senses/species unless explicitly
 * marked sensor-only or bounded-memory unit fixture. No percentage gate is lowered. */
'use strict';
const assert=require('node:assert/strict'),{World,LONG,AI,geo}=require('./lib');
const Y=LONG.y,S=[],add=(name,fn)=>S.push({name,fn:()=>({ok:true,note:fn()||'assertions passed'})});
function entity(w,kind='hound',still=false){const e=w[kind](5000,Y,{id:41});e.ang=0;e.tierT=1e9;e.rest=1e9;e.act='rest';if(still)e.sp={...e.sp,tick(){}};return e;}
function trace(e){return JSON.stringify({x:e.x,y:e.y,ang:e.ang,s:e.state,a:e.act,t:e.target,path:e.path,search:e.search,hl:e.hLight,inv:e.inv,att:e.att&&[...e.att],p:[...e.mem.p],leads:e.mem.leads,habits:[...e.mem.habits],hyp:e.mem.hypotheses});}
function sound(w,p,x=p.x,y=p.y,I=1){w.eng.sound({x,y,r:1800,I,type:'run',src:p.id});}
function hidden(kind='hound',seed=501){const w=World(seed),e=entity(w,kind,true),p=w.player(4600,Y,{light:false});w.run(.3);return {w,e,p};}
add('2F F01 unseen footstep is anonymous, uncertain, no raw origin/identity',()=>{for(const kind of ['hound','smiler']){const {w,e,p}=hidden(kind);sound(w,p);const h=e.mem.sounds.at(-1);assert(h);assert.equal(h.pid,null);assert.equal(h.src,0);assert.equal(h.attribution,'anonymous');assert(h.u>0);assert(!('ox'in h||'oy'in h));assert(!e.mem.p.has(p.id));assert(e.mem.leads.some(l=>l.k==='sound'&&l.pid===null));}return 'both species; actual hearing boundary';});
add('2F F02 a currently observed unambiguous source can be identified',()=>{for(const kind of ['hound','smiler']){const w=World(502),e=entity(w,kind,true),p=w.player(5250,Y);w.run(.3);assert(e.mem.p.get(p.id)?.seen);sound(w,p);const h=e.mem.sounds.at(-1);assert.equal(h.pid,p.id);assert.equal(h.attribution,'identified');assert(e.mem.p.get(p.id).heardAt>=w.eng.now-.01);}});
add('2F F03 two hidden sound sources stay anonymous',()=>{const {w,e,p}=hidden(),q=w.player(4400,Y,{light:false});w.run(.2);sound(w,p);sound(w,q,5700,Y);assert.equal(e.mem.sounds.length,2);assert(e.mem.sounds.every(h=>h.pid===null&&h.src===0));assert.equal(e.mem.p.size,0);assert(e.mem.leads.every(l=>l.pid===null));});
add('2F F04 private sound source ID cannot change observations or decisions',()=>{function run(id,kind){const {w,e,p}=hidden(kind);e.sp=AI.SPECIES[kind];sound(w,{id},4600,Y);const a=[];w.run(3,()=>a.push(trace(e)));return a;}for(const kind of ['hound','smiler'])assert.deepEqual(run(100,kind),run(9876,kind));});
add('2F F05 current clear sight beats weak unrelated anonymous sound',()=>{for(const kind of ['hound','smiler']){const w=World(505),e=entity(w,kind),p=w.player(5350,Y);w.run(.4);const target=e.target;assert.equal(target,p.id);sound(w,{id:3333},4600,Y,.13);w.run(.4);assert.equal(e.target,target);assert(e.evidence.candidates[0].modality==='sight');}});
add('2F F06 lost target can yield to credible new observation',()=>{const w=World(506),e=entity(w),a=w.player(5400,Y),b=w.player(900,600,{light:false});w.run(.35);assert.equal(e.target,a.id);a.x=900;a.y=600;a.light=false;b.x=e.x+260;b.y=e.y;b.light=true;e.ang=0;w.run(3.2,()=>{b.x=e.x+260;b.y=e.y;e.ang=0;});assert.equal(e.target,b.id);});
add('2F F07 anonymous light never invents an identity alongside a target',()=>{for(const kind of ['hound','smiler']){const w=World(507),e=entity(w,kind,true),p=w.player(5280,Y);w.run(.3);w.eng.obsHook=()=>[{src:null,flash:false,pts:[{x:4900,y:Y,I:.7,w:1}],air:[],fresh:true,moved:false}];w.run(.6);assert.equal(e.mem.p.size,1);assert(e.mem.p.has(p.id));assert(e.mem.leads.length);assert(e.mem.leads.every(l=>l.pid===null));}});
add('2F F08 reversed player/entity input order has identical decisions',()=>{function run(reverse){const w=World(508),h=entity(w),s=w.smiler(7500,Y,{id:42}),a=w.player(5450,Y),b=w.player(5670,Y);s.tierT=1e9;const set=w.eng.setPlayers;w.eng.setPlayers=function(ps){return set.call(this,reverse?ps.slice().reverse():ps);};const out=[];w.run(8,()=>{if(reverse)w.eng.entities.reverse();out.push([trace(h),trace(s)]);});return out;}assert.deepEqual(run(false),run(true));return '480 paired decision ticks, two species/two players';});
function branch(kind,pos,options={}){const w=World(509),e=entity(w,kind),p=w.player(5370,Y);w.run(.35);assert(e.mem.p.get(p.id)?.seen);p.stop();p.light=false;p.x=pos.x;p.y=pos.y;const out=[];if(options.light)w.eng.obsHook=()=>[{src:null,flash:false,pts:[{x:4800,y:Y,I:.4,w:0}],air:[],fresh:false,moved:true}];if(options.sound)sound(w,{id:p.id},4800,Y,.7);w.run(3,()=>out.push(trace(e)));return out;}
add('2F F09 hidden branch invariance including anonymous sound/light conflict',()=>{const positions=[{x:900,y:600},{x:8500,y:6500}];for(const k of ['hound','smiler'])for(const options of [{},{sound:true},{light:true},{sound:true,light:true}])assert.deepEqual(branch(k,positions[0],options),branch(k,positions[1],options));return '1,440 paired decision ticks';});
function habits(w,e,p){const r=e.mem.p.get(p.id);assert(r?.seen);for(let i=0;i<6;i++){const t=w.eng.now+i*2;r.visual={...r.visual,x:i%2?5400:5180,y:Y,vx:100,vy:0,t};r.seenAt=t;AI.habitObserve(e,r,t);}AI.cleanHabits(e,w.eng.now+10);return r;}
// Sensor-only body during acquisition prevents a capture from ending the fixture;
// observations, movement acceleration, footsteps and LOS are all real production logic.
function acquireReal(kind='hound') {
 const w=World(850),e=w[kind](4950,Y),p=w.player(5175,Y);e.ang=0;e.tierT=1e9;const species=e.sp;e.sp={...species,tick(){}};
 for(let i=0;i<6;i++){p.go(i%2?5175:5420,Y,'walk');w.run(2.3);if(i<4)assert.equal(e.mem.hypotheses.length,0);}
 assert(e.mem.hypotheses.some(h=>h.count>=3));assert(e.mem.habits.get(p.id).length<=6);
 return {w,e,p,species};
}
add('2F F10 three observed repetitions form bounded, modest hypothesis',()=>{for(const k of ['hound','smiler'])acquireReal(k);const w=World(510),e=entity(w,'hound',true),p=w.player(5250,Y);w.run(.3);const r=e.mem.p.get(p.id);r.visual={...r.visual,vx:100};AI.habitObserve(e,r,w.eng.now);AI.cleanHabits(e,w.eng.now);assert.equal(e.mem.hypotheses.length,0);e.mem.habits.clear();r.habitLast=null;habits(w,e,p);assert(e.mem.hypotheses.length>0);assert(e.mem.hypotheses.every(h=>h.count>=3&&h.bias<=.15));const score=AI.habitBias(e,p.id,5180,Y,10);assert.equal(score,11.2);assert.equal(AI.habitBias(e,p.id,8000,Y,10),10);return 'both species acquire from actual move.js/perception over six passages; unit score check: 12% only within plausible candidate region';});
add('2F F11 habit never learns a hidden branch and wrong prediction is fallible',()=>{function run(x){const w=World(511),e=entity(w,'hound',true),p=w.player(5250,Y);w.run(.3);const r=habits(w,e,p),before=JSON.stringify([...e.mem.habits]);r.seen=false;p.x=x;p.light=false;AI.habitObserve(e,r,w.eng.now+12);assert.equal(JSON.stringify([...e.mem.habits]),before);return [e.mem.hypotheses,AI.habitBias(e,p.id,5180,Y,10),AI.habitBias(e,p.id,8000,Y,10)];}assert.deepEqual(run(600),run(9000));
 for(const kind of ['hound','smiler']){const traces=[];for(const pos of [{x:900,y:600},{x:8500,y:6500}]){const {w,e,p,species}=acquireReal(kind);e.sp=species;w.run(.15);p.stop();p.light=false;p.x=pos.x;p.y=pos.y;const tr=[];w.run(35,()=>{assert(!p.dead);tr.push(trace(e));});assert.equal(e.mem.hypotheses.length,0);traces.push(tr);}assert.deepEqual(traces[0],traces[1]);}
 return 'real learned history; 4,200 paired hidden-branch ticks, both species; no hidden capture, hypotheses expire';});
add('2F F12 TTL and encounter end both expire habits',()=>{const w=World(512),e=entity(w,'hound',true),p=w.player(5250,Y);w.run(.3);habits(w,e,p);AI.cleanHabits(e,w.eng.now+41);assert.equal(e.mem.habits.size,0);habits(w,e,p);e.seenNow.clear();e.state='ROAMING';AI.cleanHabits(e,w.eng.now+10);assert.equal(e.mem.habits.size,0);assert.equal(e.mem.hypotheses.length,0);});
add('2F F13 death/respawn/leave/world reset clear encounter identity',()=>{for(const how of ['death','respawn','disconnect','leave','world']){const w=World(513),e=entity(w,'hound',true),p=w.player(5250,Y);w.run(.3);habits(w,e,p);AI.habitBias(e,p.id,5180,Y,10);if(how==='death'){assert(w.sim.admin.previewKill(p,'hound','A').ok);assert(p.dead);}if(how==='respawn'){p.dead=true;assert(w.sim.respawn(p));}if(how==='disconnect')w.sim.removePlayer(p);if(how==='leave'){assert(w.sim.vanish(p,1000));assert(w.sim.leave(p,1003));assert(w.sim.join(p,1003));}if(how==='world')w.eng.clear();if(how==='world'){assert.equal(w.eng.entities.length,0);assert(!w.eng.beams);assert(!w.eng.beamHist?.size);}else {assert(!e.mem.habits.has(p.id));assert(!e.mem.hypotheses.some(h=>h.pid===p.id));assert(!e.dbg.habit||e.dbg.habit.pid!==p.id);}}});
function isolated(kind,other,extra=0,spawn=false){const w=World(514),e=entity(w,kind),p=w.player(5400,Y);p.go(8000,Y,'run');const distant=w[other](900,600,{id:71});distant.tierT=1e9;const tr=[];w.run(6,()=>{for(let i=0;i<extra;i++)for(const rng of Object.values(distant.streams))rng();if(spawn&&w.t<.01)w[other](8500,6500,{id:72});tr.push(trace(e));});return tr;}
add('2F F14 / R1 extra Smiler draws cannot perturb Hound',()=>assert.deepEqual(isolated('hound','smiler'),isolated('hound','smiler',17)));
add('2F F15 / R2 extra Hound draws cannot perturb Smiler',()=>assert.deepEqual(isolated('smiler','hound'),isolated('smiler','hound',17)));
add('2F F16 / R3 unrelated spawn and initialization preserve old streams',()=>{for(const [a,b] of [['hound','smiler'],['smiler','hound']])assert.deepEqual(isolated(a,b),isolated(a,b,0,true));});
add('2F F17 / R4 / R5 repeatable streams and IR/debug metadata isolation',()=>{assert.deepEqual(isolated('hound','smiler'),isolated('hound','smiler'));const w=World(517),h=entity(w),s=w.smiler(7500,Y,{id:71});assert.notDeepEqual(h.tr,s.tr);const x=World(517),hh=entity(x);for(let i=0;i<20;i++){w.eng.debugInfo();assert.equal(h.streams.behavior(),hh.streams.behavior());}return 'same seed/ID/tag repeatability; debug makes no RNG draws';});
add('2F F18 evidence pressure obeys all advertised caps',()=>{const w=World(518),e=entity(w,'hound',true);for(let i=0;i<40;i++)w.player(5230+i*2,Y,{light:true});w.run(.4);for(let n=0;n<600;n++){sound(w,{id:9999},4400+n%1500,Y,.8);e.mem.visited.set(n,w.eng.now);if(n%10===0)w.run(.12);}assert(e.mem.p.size<=AI.INTEL.players);assert(e.mem.leads.length<=6);assert(e.mem.sounds.length<=8);w.run(.2);assert(e.mem.visited.size<=128);assert(e.mem.hypotheses.length<=3);assert([...e.mem.p.values()].every(r=>r.ev.length<=4));assert(e.evidence.candidates.length<=12);return JSON.stringify(w.eng.debugInfo().ents?.length||AI.INTEL);});
add('2F F19 disconnect immediately removes target, attention, habits, identified sound',()=>{for(const kind of ['hound','smiler']){const w=World(519),e=entity(w,kind),p=w.player(5330,Y);w.run(.5);assert(e.mem.p.has(p.id));sound(w,p);w.sim.removePlayer(p);assert(!e.mem.p.has(p.id));assert.notEqual(e.target,p.id);assert(!e.att?.has(p.id));assert(!e.mem.sounds.some(h=>h.pid===p.id));}});
function metadata(kind,secret){const w=World(520),e=entity(w,kind),p=w.player(5370,Y,{kind:'camcorder'});p.go(8000,Y,'walk');const out=[];w.run(5,()=>{p.ir=secret?2:0;p.irNet=p.ir;p.irLevel=p.ir;p.nvOn=!!secret;p.hp=secret?1:100;p.inventory=secret?['powerbulb']:[];p.accountId=secret?'hidden_A':'hidden_B';out.push(trace(e));});return out;}
add('2F F20 IR OFF/HIGH is tick-identical for both species',()=>{for(const k of ['hound','smiler'])assert.deepEqual(metadata(k,0),metadata(k,1));return '600 paired decision ticks, real movement';});
add('2F F21 hidden HP, inventory and account metadata cannot influence decisions',()=>{for(const k of ['hound','smiler'])assert.deepEqual(metadata(k,0),metadata(k,1));});
add('2F F22 species physical/canon parameter preservation',()=>{const fs=require('fs'),path=require('path'),crypto=require('crypto'),M=require('../STAGE_2F_PRESERVATION.json'),baseline=process.env.STAGE2E_BASELINE;
 const before=baseline?require(path.resolve(baseline,'ai.js')).SPECIES:M.species;
 assert.deepEqual(JSON.parse(JSON.stringify(AI.SPECIES)),JSON.parse(JSON.stringify(before)));
 for(const [f,hash]of Object.entries(M.unchanged_sha256))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.resolve(__dirname,'../..',f))).digest('hex'),hash,f);
 return 'all species data properties and '+Object.keys(M.unchanged_sha256).length+' frozen movement/death/nav/network/presentation source hashes';});
add('2F F23 long-run mixed lifecycle validity',()=>{const w=World(523),es=[entity(w),w.smiler(7100,Y,{id:42}),w.hound(8300,Y,{id:43})],ps=[w.player(5450,Y),w.player(7550,Y)];let ticks=0,respawns=0;w.run(180,()=>{ticks++;for(const p of ps){if(p.dead){assert(w.sim.respawn(p));p.safe=0;p.x=5450+(p.id-100)*2100;p.y=Y;respawns++;}if(ticks%900===0){p.light=!p.light;p.go(p.x<6500?8500:3500,Y,ticks%1800?'run':'crouch');}}for(const e of es){assert([e.x,e.y,e.speed,e.ang].every(Number.isFinite));assert(AI.S[e.state]);assert(!e.target||e.mem.p.has(e.target));assert(e.mem.p.size<=16&&e.mem.sounds.length<=8&&e.mem.leads.length<=6&&e.mem.hypotheses.length<=3&&e.mem.visited.size<=128);}});for(const p of ps){w.sim.removePlayer(p);p.active=false;}for(const e of es)assert.equal(e.mem.p.size,0);
 for(let cycle=0;cycle<4;cycle++){const q=w.player(5450,Y);w.run(2);w.sim.removePlayer(q);q.active=false;for(const e of es){assert(!e.mem.p.has(q.id));assert(!e.mem.habits.has(q.id));assert.notEqual(e.target,q.id);}}return `${ticks} mixed ticks; ${respawns} actual respawns; four disconnect/rejoin cycles with no stale identity`;});
module.exports=S;
