/* Stage F shared wire contract. Full precision: quantization cannot choose support. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./world_motion'));else root.TFB_PROTOCOL=factory(root.TFB_MOTION);})(typeof self!=='undefined'?self:this,function(M){
'use strict';
const VERSION=1,CAPS=Object.freeze(['spatial-pose-v1','ordered-proposals-v1','explicit-epochs-v1']),LIMIT=Object.freeze({coordinate:1e7,velocity:2000,history:90,queue:90,samples:15,work:15,delay:.1,extrapolate:.15});
const finite=(x,b=LIMIT.coordinate)=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<=b;
const integer=x=>Number.isSafeInteger(x)&&x>=0;
const id=x=>typeof x==='string'&&x.length>0&&x.length<=128;
const ref=x=>x===null||id(x);
function manifest(g,epoch,tick){const i=g.identity,d=g.definition;return {version:VERSION,capabilities:[...CAPS],worldEpoch:epoch,geometryMode:i.geometryMode,schemaVersion:i.schemaVersion,geometryRevision:i.geometryRevision||i.contentRevision,geometryHash:i.contentHash,motionRevision:M.POLICY.version,simTick:tick,ids:{support:(d.supportPatches||[]).map(p=>p.id).sort(),surface:(d.navSurfaces||[]).map(p=>p.id).sort(),link:(d.traversalLinks||[]).map(p=>p.id).sort()}};}
function compatible(a,b){if(!a||!b||a.version!==VERSION||!Array.isArray(a.capabilities)||CAPS.some(c=>!a.capabilities.includes(c)))return 'protocol-capabilities';for(const k of ['geometryMode','schemaVersion','geometryRevision','geometryHash','motionRevision'])if(a[k]!==b[k])return k;return null;}
function pose(body,identity,g){const s=body.supportId||null,t=body.trav;const p={...identity,x:body.x,y:body.y,z:body.z??0,vx:body.vx||0,vy:body.vy||0,vz:body.vz||0,yaw:body.angle??body.ang??0,height:body.shape?.height??60,profile:body.shape?.id||'profile:player-stand',support:s,navSurface:s?g.supportPatch(s)?.navSurfaceId||null:null,mode:body.dead?'dead':body.caught?'captured':body.netVault?'traversal':body.motionMode||'grounded',link:body.netVault?.linkId||t?.link?.id||null,progress:body.netVault?body.netVault.t/body.netVault.dur:t?Math.min(1,t.ticks*M.POLICY.dt/(t.duration||1)):0,discontinuity:identity.discontinuity||0,vault:body.netVault?JSON.parse(JSON.stringify(body.netVault)):null,step:body.step?{...body.step}:null,traversal:t?{segment:t.segment,status:t.status,ticks:t.ticks,start:t.start,finish:t.finish,distance:t.distance,top:t.top,duration:t.duration,settling:!!t.settling,speed:body.traversalSpeed||172}:null};return validPose(p)?p:null;}
function validTransition(p){if(p.vault){const v=p.vault;if(!['sx','sy','ex','ey','dur','t','nx','ny','exitSpeed'].every(k=>finite(v[k]))||v.dur<=0||v.dur>2||v.t<0||v.t>v.dur||!id(v.linkId)||!v.physical||!['start','finish'].every(k=>v.physical[k]&&['x','y','z'].every(c=>finite(v.physical[k][c])))||!finite(v.physical.top))return false;}if(p.step&&(!['startZ','targetZ','t','duration','dx','dy'].every(k=>finite(p.step[k]))||!id(p.step.targetId)||!['raise','forward'].includes(p.step.phase)))return false;if(p.traversal&&(!integer(p.traversal.ticks)||p.traversal.ticks>100000||!integer(p.traversal.segment)||!['start','finish'].every(k=>p.traversal[k]&&['x','y','z'].every(c=>finite(p.traversal[k][c])))))return false;return true;}
function validPose(p){return validTransition(p||{})&& !!p&&id(p.worldEpoch)&&id(p.entityId)&&integer(p.generation)&&integer(p.tick)&&integer(p.seq)&&integer(p.discontinuity)&&['x','y','z'].every(k=>finite(p[k]))&&['vx','vy','vz'].every(k=>finite(p[k],LIMIT.velocity))&&finite(p.yaw,100)&&finite(p.height,1000)&&p.height>0&&id(p.profile)&&ref(p.support)&&ref(p.navSurface)&&ref(p.link)&&finite(p.progress,1)&&p.progress>=0&&['grounded','airborne','step','traversal','captured','dead','sleeping'].includes(p.mode);}
class Client {
 constructor(local){this.local=local;this.reset();}
 reset(){this.world=null;this.life=0;this.ack=0;this.seq=0;this.tick=0;this.predictionTick=0;this.pending=[];this.pose=null;this.anchor=null;this.error=null;}
 hello(m){const err=compatible(this.local,m);if(err){this.error=err;return {t:'hello',protocol:{...this.local,worldEpoch:m.worldEpoch}};}if(this.world?.worldEpoch!==m.worldEpoch)this.reset();this.world=m;this.tick=m.simTick;return {t:'hello',protocol:{...this.local,worldEpoch:m.worldEpoch}};}
 accept(p){if(!validPose(p)||p.worldEpoch!==this.world?.worldEpoch||p.generation<this.life||(p.generation===this.life&&p.discontinuity<this.ack))return false;if(p.generation===this.life&&p.discontinuity===this.ack&&this.pose&&p.tick<this.pose.tick)return false;const boundary=p.generation!==this.life||p.discontinuity!==this.ack;this.life=p.generation;this.ack=p.discontinuity;this.pose=p;this.tick=Math.max(this.tick,p.tick);if(boundary){this.pending=[];this.tick=p.tick;this.predictionTick=p.tick;this.anchor=p;}return true;}
 record(body,mv,vault,geometry){if(!this.anchor)return;this.pending.push({tick:++this.predictionTick,x:body.x,y:body.y,z:body.z,vx:body.vx,vy:body.vy,yaw:body.angle||0,posture:body.posture||'stand',support:body.supportId,mv,...(vault?{vault:{link:geometry.definition.traversalLinks.find(l=>l.obstacleId===vault.p.id)?.id,quality:vault.q}}:{})});if(this.pending.length>LIMIT.queue){this.pending=[];return this.action({t:'resync'});}return null;}
 flush(){const count=this.pending.findIndex(q=>q.tick>this.tick),n=Math.min(LIMIT.samples,count<0?this.pending.length:count);return n?this.proposal(this.pending.splice(0,n)):null;}
 action(m){return {...m,worldEpoch:this.world?.worldEpoch,life:this.life,ack:this.ack};}
 rebase(body,g,motor){const p=this.anchor;if(!p)return false;M.create(g).initialize(Object.assign(body,{x:p.x,y:p.y,z:p.z,vx:p.vx,vy:p.vy,vz:p.vz,angle:p.yaw}),Object.keys(M.PROFILES).find(k=>M.PROFILES[k].id===p.profile)||'stand');body.supportId=p.support;body.motionMode=p.mode==='captured'||p.mode==='dead'?'grounded':p.mode;body.step=p.step?{...p.step}:null;body.trav=null;body.netVault=p.vault?JSON.parse(JSON.stringify(p.vault)):null;if(motor){motor.vault=p.vault?JSON.parse(JSON.stringify(p.vault)):null;if(p.vault)motor.s='vault';}return true;}
 proposal(samples,extra={}){if(!this.world)throw Error('Handshake required');return {...extra,t:'sp',worldEpoch:this.world.worldEpoch,geometryHash:this.world.geometryHash,life:this.life,seq:++this.seq,ack:this.ack,samples};}
}
return Object.freeze({VERSION,CAPS,LIMIT,finite,integer,id,manifest,compatible,pose,validPose,Client});
});
