/* Shared geometry boundary — Stage B, explicit preserved planar fast path only.
 * Data lives in levels/level0.js. Spatial query names below deliberately throw.
 * No physical-Z solving, time reads, RNG, perception or species decisions. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TFB_GEOMETRY=factory();})(typeof self!=='undefined'?self:this,function(){
'use strict';
function freeze(v){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}
function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';}
// Synchronous SHA-256 over UTF-8, identical in classic browser scripts and Node.
function sha256(s){
 const K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
 const input=new TextEncoder().encode(s),n=input.length,bytes=new Uint8Array(Math.ceil((n+9)/64)*64);bytes.set(input);bytes[n]=128;
 const dv=new DataView(bytes.buffer);dv.setUint32(bytes.length-8,Math.floor(n/0x20000000));dv.setUint32(bytes.length-4,(n*8)>>>0);
 const H=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19],W=new Uint32Array(64),rr=(x,n)=>(x>>>n)|(x<<(32-n));
 for(let off=0;off<bytes.length;off+=64){for(let i=0;i<16;i++)W[i]=dv.getUint32(off+i*4);for(let i=16;i<64;i++){const x=W[i-15],y=W[i-2];W[i]=(W[i-16]+(rr(x,7)^rr(x,18)^(x>>>3))+W[i-7]+(rr(y,17)^rr(y,19)^(y>>>10)))>>>0;}
 let [a,b,c,d,e,f,g,h]=H;for(let i=0;i<64;i++){const t1=(h+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^(~e&g))+K[i]+W[i])>>>0,t2=((rr(a,2)^rr(a,13)^rr(a,22))+((a&b)^(a&c)^(b&c)))>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}for(const [i,x] of [a,b,c,d,e,f,g,h].entries())H[i]=(H[i]+x)>>>0;
 }return H.map(x=>x.toString(16).padStart(8,'0')).join('');
}
function contentHash(d){const {contentHash,...data}=d;return sha256(canonical(data));}
function validate(d){
 const ok=(x,msg)=>{if(!x)throw Error('WorldDefinition: '+msg);},num=x=>typeof x==='number'&&Number.isFinite(x),int=x=>Number.isInteger(x),str=x=>typeof x==='string'&&x.length>0,arr=(x,n)=>{ok(Array.isArray(x),n+' array');return x;};
 function finite(v){ok(v===null||['object','string','number','boolean'].includes(typeof v),'JSON data only');if(typeof v==='number')ok(num(v),'nonfinite number');else if(v&&typeof v==='object')Object.values(v).forEach(finite);}
 finite(d);ok(d&&d.schemaVersion===1,'schema mismatch');ok(d.geometryMode==='flat-compat','unsupported geometry mode (spatial is Stage C)');ok(str(d.assetId)&&str(d.contentRevision),'identity');ok(d.units==='legacy-world-unit','units');ok(d.spatialRecords===null&&d.verticalExtent==='UNSPECIFIED — NOT SPATIAL GEOMETRY','flat cannot claim spatial geometry');
 const f=d.flat,b=d.bounds;ok(f&&b&&b.min&&b.max,'bounds/flat descriptor');
 ok(int(f.width)&&int(f.height)&&f.width>0&&f.height>0&&f.width*f.height<=1000000,'grid bounds');ok(f.tile===96&&f.navCell===48&&f.navRadius===21,'unsupported legacy metric');
 ok(b.min.x===0&&b.min.y===0&&b.min.z===null&&b.max.z===null&&b.max.x===f.width*f.tile&&b.max.y===f.height*f.tile,'malformed bounds');
 const ids=new Set(),id=v=>{ok(str(v)&&!ids.has(v),'duplicate/invalid ID '+v);ids.add(v);};
 const materials=new Set(arr(d.materials,'materials'));ok(materials.size===d.materials.length&&d.materials.every(str),'material IDs');ok(materials.has(d.defaultMaterial),'default material reference');
 const rect=r=>{ok(['x','y','w','h'].every(k=>int(r[k]))&&r.w>0&&r.h>0&&r.x>=0&&r.y>=0&&r.x+r.w<=f.width&&r.y+r.h<=f.height,'rectangle bounds');};
 const rooms=new Set();arr(f.rooms,'rooms').forEach(r=>{id(r.id);ok(str(r.code)&&str(r.name),'room names');ok(r.id==='room:'+r.code,'room identity');rect(r);rooms.add(r.id);});
 ok(d.roomMaterials&&typeof d.roomMaterials==='object'&&!Array.isArray(d.roomMaterials),'room materials');for(const [name,mat] of Object.entries(d.roomMaterials)){ok(f.rooms.some(r=>r.name===name),'room material reference');ok(materials.has(mat),'material reference');}
 for(const key of ['floorCarves','wallCarves','doorCarves'])arr(f[key],key).forEach(a=>{ok(Array.isArray(a)&&a.length===4,'carve rectangle');rect({x:a[0],y:a[1],w:a[2],h:a[3]});});
 arr(f.columns,'columns').forEach(c=>{id(c.id);rect({x:c.x,y:c.y,w:1,h:1});});
 const pg=f.pillarGrid;ok(pg&&num(pg.half)&&pg.half>0&&pg.size===pg.half*2,'pillar profile');arr(pg.xs,'pillar xs').forEach(x=>ok(num(x)&&x*f.tile-pg.half>=0&&x*f.tile+pg.half<=b.max.x,'pillar x'));arr(pg.ys,'pillar ys').forEach(y=>ok(num(y)&&y*f.tile-pg.half>=0&&y*f.tile+pg.half<=b.max.y,'pillar y'));arr(pg.ids,'pillar IDs').forEach(id);ok(pg.ids.length===pg.xs.length*pg.ys.length,'pillar ID count');
 const lr=f.lampRule;ok(lr&&rooms.has(lr.excludeRoomId),'lamp room reference');ok(int(lr.offset)&&lr.offset>=0&&int(lr.stride)&&lr.stride>0&&int(lr.margin)&&lr.margin>=0&&num(lr.center)&&lr.center>=0&&lr.center<1,'lamp generation rule');arr(f.lampIds,'lamp IDs').forEach(id);
 arr(f.propDefs,'props').forEach(p=>{id(p.id);ok(['low','under','gap','window'].includes(p.type)&&str(p.kind),'prop type/kind');rect({x:p.tx,y:p.ty,w:p.tw,h:p.th});if(p.type==='gap'||p.type==='window')ok(['x','y'].includes(p.axis),'prop axis');if(p.type!=='gap')ok(num(p.depth)&&p.depth>0&&p.depth<=96,'prop depth');});
 const li=f.legacyItems;ok(li,'legacy items');arr(li.roomIds,'item rooms').forEach(r=>ok(rooms.has(r),'item room reference'));arr(li.ids,'item IDs').forEach(id);ok(li.ids.length===li.roomIds.length,'item ID count');
 const point=p=>ok(num(p.x)&&num(p.y)&&p.x>=0&&p.y>=0&&p.x<=b.max.x&&p.y<=b.max.y,'anchor bounds');
 arr(f.patrol,'patrol').forEach(p=>{id(p.id);point(p);});arr(d.anchors,'anchors').forEach(a=>{id(a.id);point(a);ok(a.z===0&&a.supportId===null,'flat anchor');});for(const a of ['spawn:player','anchor:reachability'])ok(d.anchors.some(x=>x.id===a),'missing anchor '+a);
 ok(d.exits&&d.exits.kind==='seeded-glitched-walls'&&d.exits.owner==='dev/sim_glue.js'&&Array.isArray(d.exits.staticAnchors)&&d.exits.staticAnchors.length===0,'exit generation reference');
 ok(typeof d.contentHash==='string'&&/^[a-f0-9]{64}$/.test(d.contentHash)&&contentHash(d)===d.contentHash,'content hash mismatch');
 return true;
}

function compile(definition,WORLD){
 validate(definition);
 if(!WORLD||!WORLD.levelDefinition||WORLD.levelDefinition.contentHash!==definition.contentHash)throw Error('WORLD definition mismatch');
 const D=freeze(JSON.parse(JSON.stringify(definition))),F=D.flat;
 const anchorXY=id=>{const a=D.anchors.find(a=>a.id===id);if(!a)throw Error('Unknown anchor '+id);return {x:a.x,y:a.y};};
 var FBW=F.width,FBH=F.height,Oc=F.rooms.map(({id,...r})=>r),kc=new Uint8Array(FBW*FBH);function Ac(e,t,n,r){for(let i=t;i<t+r;i++)for(let t=e;t<e+n;t++)t>=0&&i>=0&&t<FBW&&i<FBH&&(kc[i*FBW+t]=1)}function jc(e,t,n,r){for(let i=t;i<t+r;i++)for(let t=e;t<e+n;t++)t>=0&&i>=0&&t<FBW&&i<FBH&&(kc[i*FBW+t]=0)}Oc.forEach(e=>Ac(e.x,e.y,e.w,e.h)),F.floorCarves.forEach(e=>Ac(...e)),F.wallCarves.forEach(e=>jc(...e)),F.doorCarves.forEach(e=>Ac(...e));WORLD.carve(kc,FBW);var Mc=F.columns.map(({id,...p})=>p);for(let e of Mc)jc(e.x,e.y,1,1);var Nc=[];for(let e=0;e<FBH;e++)for(let t=0;t<FBW;t++)kc[e*FBW+t]||Nc.push({x:t*96,y:e*96,w:96,h:96});var Pc=[];for(let e of F.pillarGrid.xs)for(let t of F.pillarGrid.ys)Pc.push({x:e*96-F.pillarGrid.half,y:t*96-F.pillarGrid.half,w:F.pillarGrid.size,h:F.pillarGrid.size});var Fc=[];Oc.forEach((e,t)=>{if(F.rooms[t].id!==F.lampRule.excludeRoomId)for(let n=e.x+F.lampRule.offset;n<e.x+e.w-F.lampRule.margin;n+=F.lampRule.stride)for(let r=e.y+F.lampRule.offset;r<e.y+e.h-F.lampRule.margin;r+=F.lampRule.stride)kc[r*FBW+n]&&Fc.push({x:(n+F.lampRule.center)*96,y:(r+F.lampRule.center)*96})});var Ic=anchorXY("spawn:player");
var zc=(e,t)=>e>=0&&t>=0&&e<FBW&&t<FBH&&kc[t*FBW+e]===1;function Bc(e,t){let n=[],r=Math.floor(e/96),i=Math.floor(t/96);for(let e=i-1;e<=i+1;e++)for(let t=r-1;t<=r+1;t++)zc(t,e)||n.push({x:t*96,y:e*96,w:96,h:96});for(let r of Pc)Math.abs(r.x-e)<250&&Math.abs(r.y-t)<250&&n.push(r);return WORLD.addNear(n,e,t)}var Vc=new Set(Mc.map(e=>e.y*FBW+e.x)),Hc=(e,t)=>e<0||t<0||e>=FBW||t>=FBH||!zc(e,t)&&!Vc.has(t*FBW+e);function Uc(e,t,n,r){let i=Math.cos(n),a=Math.sin(n),o=i>=0?1:-1,s=a>=0?1:-1,c=Math.floor(e/96),l=Math.floor(t/96),u=r;if(Hc(c,l))return 0;let d=Math.abs(i)<1e-10?1/0:96/Math.abs(i),f=Math.abs(a)<1e-10?1/0:96/Math.abs(a),p=Math.abs(i)<1e-10?1/0:((c+ +(o>0))*96-e)/i,m=Math.abs(a)<1e-10?1/0:((l+ +(s>0))*96-t)/a;for(;Math.min(p,m)<u;)if(Math.abs(p-m)<1e-8){let e=p;if(Hc(c+o,l)||Hc(c,l+s)){u=e;break}if(c+=o,l+=s,p+=d,m+=f,Hc(c,l)){u=e;break}}else if(p<m){let e=p;if(c+=o,p+=d,Hc(c,l)){u=e;break}}else{let e=m;if(l+=s,m+=f,Hc(c,l)){u=e;break}}for(let n of Pc){if(Math.abs(i)<1e-10&&(e<n.x||e>n.x+n.w)||Math.abs(a)<1e-10&&(t<n.y||t>n.y+n.h))continue;let r=Math.abs(i)<1e-10?-1/0:(n.x-e)/i,o=Math.abs(i)<1e-10?1/0:(n.x+n.w-e)/i,s=Math.abs(a)<1e-10?-1/0:(n.y-t)/a,c=Math.abs(a)<1e-10?1/0:(n.y+n.h-t)/a,l=Math.max(Math.min(r,o),Math.min(s,c));Math.min(Math.max(r,o),Math.max(s,c))>=Math.max(0,l)&&l>=0&&(u=Math.min(u,l))}return Math.max(0,u)}
var el=F.legacyItems.roomIds.map(id=>F.rooms.findIndex(r=>r.id===id)).map(e=>{let t=Oc[e],n=(t.x+t.w*.48)*96,r=(t.y+t.h*.55)*96;return Bc(n,r).some(e=>Math.hypot(n-Math.max(e.x,Math.min(n,e.x+e.w)),r-Math.max(e.y,Math.min(r,e.y+e.h)))<48)&&(n=(t.x+t.w*.7)*96,r=(t.y+t.h*.35)*96),{x:n,y:r,found:!1,room:t.name}});
var il=F.navCell,W=FBW*2,al=FBH*2,ol=F.navRadius;function sl(e,t,n=ol){return Bc(e,t).every(r=>Math.hypot(e-Math.max(r.x,Math.min(e,r.x+r.w)),t-Math.max(r.y,Math.min(t,r.y+r.h)))>=n)}function cl(e,t,n=ol){let r=Math.hypot(t.x-e.x,t.y-e.y),i=Math.ceil(r/12);for(let r=0;r<=i;r++){let a=i?r/i:0;if(!sl(e.x+(t.x-e.x)*a,e.y+(t.y-e.y)*a,n))return!1}return!0}var ll=new Uint8Array(W*al);for(let e=0;e<al;e++)for(let t=0;t<W;t++){let n=(t+.5)*il,r=(e+.5)*il;ll[e*W+t]=Number(zc(Math.floor(n/96),Math.floor(r/96))&&sl(n,r))}var ul=e=>({x:(e%W+.5)*il,y:(Math.floor(e/W)+.5)*il});function dl(e,t=!1){let n=-1,r=1/0,i=Math.floor(e.x/il),a=Math.floor(e.y/il);for(let o=Math.max(0,a-4);o<=Math.min(al-1,a+4);o++)for(let a=Math.max(0,i-4);a<=Math.min(W-1,i+4);a++){let i=o*W+a;if(!ll[i])continue;let s=ul(i),c=Math.hypot(e.x-s.x,e.y-s.y);c<r&&cl(e,s,t?1:ol)&&(n=i,r=c)}return n}function fl(e,t){let n=dl(e),r=dl(t,!0);if(n<0||r<0)return[];let i=new Int32Array(W*al).fill(-1),a=new Int32Array(W*al),o=0,s=1;for(a[0]=n,i[n]=n;o<s&&i[r]<0;){let e=a[o++];for(let t of[e-1,e+1,e-W,e+W])t<0||t>=W*al||!ll[t]||i[t]>=0||Math.abs(t%W-e%W)+Math.abs(Math.floor(t/W)-Math.floor(e/W))===1&&(i[t]=e,a[s++]=t)}if(i[r]<0)return[];let c=[];for(let e=r;e!==n;e=i[e])c.push(ul(e));return c.push(ul(n)),c.reverse(),cl(ul(r),t)&&c.push({...t}),c}function pl(e,t,n,r=ol){let i={...e};for(let a of[`x`,`y`]){e[a]+=a===`x`?t:n;for(let t of Bc(e.x,e.y)){let n=e.x-Math.max(t.x,Math.min(e.x,t.x+t.w)),o=e.y-Math.max(t.y,Math.min(e.y,t.y+t.h)),s=Math.hypot(n,o);s<r&&(s>0?(e.x+=n/s*(r-s),e.y+=o/s*(r-s)):e[a]=i[a])}}}

 if(Fc.length!==F.lampIds.length||Pc.length!==F.pillarGrid.ids.length)throw Error('Generated identity count mismatch');
 const materialProfileHash=sha256(canonical(WORLD.SURF));
 const identity=Object.freeze({schemaVersion:D.schemaVersion,assetId:D.assetId,contentRevision:D.contentRevision,contentHash:D.contentHash,geometryMode:D.geometryMode,materialProfileHash});
 const withMode=(mode,fn)=>{WORLD.setMode(mode||'walk');try{return fn();}finally{WORLD.setMode('walk');}};
 const planar=Object.freeze({floor:zc,clear:(x,y,r,mode)=>withMode(mode,()=>sl(x,y,r)),blockers:(x,y,mode)=>withMode(mode,()=>Bc(x,y)),ray:Uc,surfaceAt:(x,y)=>WORLD.surfaceAt(x,y,Oc),crawlAt:(x,y,pad)=>WORLD.crawlAt(x,y,pad),lowZone:(x,y,pad)=>WORLD.lowZone(x,y,pad),anchorXY,lamp:id=>{const i=F.lampIds.indexOf(id);return i<0?null:{...Fc[i]};}});
 const flat=Object.freeze({FBW,FBH,Oc,kc,Mc,Nc,Pc,Fc,Ic,zc,Bc,Hc,Uc,el,il,W,al,ol,sl,cl,ll,ul,dl,fl,pl,patrol:F.patrol.map(({id,...p})=>p)});
 const bindAdapter=dynamic=>({key:D.assetId+':'+D.contentHash+':'+materialProfileHash,cols:W,rows:al,cell:il,W:FBW*96,H:FBH*96,rooms:Oc,lamps:Fc,floor:planar.floor,clear:planar.clear,blockers:planar.blockers,ray:planar.ray,blackout:dynamic.blackout,qc:dynamic.qc,kinds:dynamic.kinds});
 const spatial=Object.fromEntries(['supports','clearance','sweep','raycast','contact','traceSupportMotion'].map(name=>[name,()=>{throw Error(name+': NOT IMPLEMENTED BY DESIGN — Stage C');}]));
 return Object.freeze({definition:D,identity,flat,planar,bindAdapter,...spatial});
}
return Object.freeze({validate,compile,canonical,sha256,contentHash});
});
