'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),{make,save,pick}=require('./trace_io');
Date.now=()=>0;const {World}=require('../harness'),B=require('../tests/nav_bench');
const out=path.resolve(process.argv[2]||path.join(__dirname,'traces')),F=B.fixtures(),g=F.G.g,P=B.pairs(F,40,11),T=make('navigation/Level0-routes',11,'dev/ai_src/10_geo.js',{pairSeed:11,pairCount:40},['Real Level 0 Geo.path and navGo. Route queries use explicit fixture caps; no future nav surfaces exist. Per-tick motor trace retains three routes for 360 ticks each; full route arrivals are in baseline NV01.']);
const caps={hound:{CAN_VAULT:true,VAULT_SPEED:1.2,CAN_CRAWL:true,CAN_USE_TIGHT_GAPS:true},smiler:{CAN_VAULT:true,VAULT_SPEED:.6,CAN_CRAWL:false,CAN_USE_TIGHT_GAPS:false}};
const route=p=>p&&p.map(q=>({...pick(q,['x','y','c']),link:q.link?pick(q.link,['to','ax','ay','bx','by','cost']):null}));let diagonals=0,crawl=0,vault=0;
for(const [i,p] of P.entries())for(const [species,c] of Object.entries(caps)){const raw=g.path(p.a.x,p.a.y,p.b.x,p.b.y,c);assert(raw);let prev=g.cellOf(p.a.x,p.a.y);for(const q of raw){const next=g.cellOf(q.x,q.y),dx=next%g.cols-prev%g.cols,dy=Math.floor(next/g.cols)-Math.floor(prev/g.cols);if(!q.link&&Math.abs(dx)===1&&Math.abs(dy)===1){assert(g.passableFor(Math.floor(prev/g.cols)*g.cols+next%g.cols,c));assert(g.passableFor(Math.floor(next/g.cols)*g.cols+prev%g.cols,c));diagonals++;}prev=next;if(q.c>=2){assert(species==='hound');crawl++;}if(q.link)vault++;}T.records.push({tick:0,query:i,species,input:p,caps:c,raw:route(raw)});}
const normal=F.floor.find(a=>g.lineClear(a.x,a.y,a.x+96,a.y,20,'walk'));assert(normal);T.records.push({tick:0,query:'normal',raw:route(g.path(normal.x,normal.y,normal.x+96,normal.y,caps.hound))});
const unreachable=g.path(P[0].a.x,P[0].a.y,-1000,-1000,caps.hound);assert.equal(unreachable,null);T.records.push({tick:0,query:'unreachable',goal:{x:-1000,y:-1000},raw:unreachable});
for(let i=0;i<3;i++){const p=P[i],w=World(900+i);w.player(9000,60,{light:false}).stop('stand');const e=w.hound(p.a.x,p.a.y);w.eng.navGo(e,{x:p.b.x,y:p.b.y,speed:292,arrive:22});for(let tick=1;tick<=360;tick++){w.step();T.records.push({tick,routeCase:i,body:pick(e,['x','y','ang','mode','speed']),path:route(e.path),goal:e.goal,nav:pick(e.nav,['plans','direct','recover','contacts','bonks','why']),traversal:pick(e.trav,['t','dur','kind']),active:!!e.navGo});}}
const ci=[...g.cls].findIndex(c=>c===2);assert(ci>=0);const cp={x:g.cx(ci),y:g.cy(ci)};const cr=g.path(cp.x,cp.y,cp.x+48,cp.y,caps.hound);assert(cr&&cr.some(q=>q.c>=2));crawl+=cr.filter(q=>q.c>=2).length;assert(!g.passableFor(ci,caps.smiler));T.records.push({tick:0,query:'crawl-only-cell',input:cp,houndPath:route(cr),smilerCellPassable:g.passableFor(ci,caps.smiler)});
assert(diagonals>0&&crawl>0&&vault>0);T.coverage={diagonals,crawlCells:crawl,vaultLinks:vault,queries:83,commitmentTicks:1080};const index=[save(out,'navigation-level0',T)];fs.writeFileSync(path.join(out,'navigation-index.json'),JSON.stringify(index,null,2)+'\n');console.log(T.coverage);
