'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),{root,make,save,pick,clean}=require('./trace_io');
Date.now=()=>0;const {World}=require('../harness'),{geo}=require('../tests/lib'),DP=require(path.join(root,'death_srv.js')).DP;
const out=path.resolve(process.argv[2]||path.join(__dirname,'traces')),index=[];
for(const kind of ['Hound','Smiler'])for(const v of ['A','B','C','D']){const w=World(810),c=kind==='Hound'&&v==='C'?geo().walls[0]:{x:5000,y:3504,ang:0,d:80};const input={kind,v,victim:{x:c.x,y:c.y,angle:0},src:{x:c.x-Math.cos(c.ang)*46,y:c.y-Math.sin(c.ang)*46},w:kind==='Hound'&&v==='C'?[c.x+Math.cos(c.ang)*c.d,c.y+Math.sin(c.ang)*c.d,c.ang]:null,vx:45,vy:0,exhausted:v==='D',eqKind:'flashlight',hat:'cap',walls:(x,y)=>w.sim.blockersAt(x,y),clear:(x,y,r)=>w.sim.clearAt(x,y,r)};
 const result=DP.simulate(input),S=DP.create(result.S.ctx),T=make('death/'+kind+'/'+v,result.S.ctx.seed,'dphys.js',clean(input),['Shared production dphys via death_srv. World-Z is not implemented. Hand damping is not elevation.']);T.plan=DP.PLAN(kind,v,input.w?Math.hypot(input.w[0]-c.x,input.w[1]-c.y):40);T.kernelContext=clean(result.S.ctx);T.planVersion='v23.3.6 dphys source hash';T.substepRate=240;let cursor=0;
 for(let tick=0;tick<=Math.ceil(result.dur*60);tick++){DP.advance(S,Math.min(result.dur,tick/60));T.records.push({tick,substep:S.stepN,body:pick(S.b,['x','y','vx','vy','th','om','sq','sqv','cs','csv']),hands:S.h.map(h=>({...pick(h,['x','y','vx','vy','brace','k']),dampingRatio:h.z})),equipment:pick(S.eq,['has','held','x','y','vx','vy','rot','w','st']),hat:pick(S.hat,['has','on','x','y','vx','vy','rot','w','st']),attacker:pick(S.at,['x','y','vx','vy','a','contact']),impacts:S.ev.slice(cursor),state:S.state,phase:S.phase});cursor=S.ev.length;}
 assert.deepStrictEqual(clean(DP.remains({ph:S})),clean(result.remains));T.finalRemains=DP.remains({ph:S});index.push(save(out,'death-'+kind+'-'+v,T));console.log(kind,v,T.records.length,'frames',S.stepN,'substeps');}
fs.writeFileSync(path.join(out,'death-index.json'),JSON.stringify(index,null,2)+'\n');
