'use strict';
// Test-only read-only observer installed around harness stepping. No source rewrites or RNG draws.
const fs=require('fs'),path=require('path'),assert=require('assert'),{root,make,save,pick,clean}=require('./trace_io');
const out=path.resolve(process.argv[2]||path.join(__dirname,'traces')),H=require('../harness');let clockTick=0;Date.now=()=>clockTick*1000/60;
const Original=H.World;let active=null,worldN=0,tracked=0;
function entity(e){const r=pick(e,['id','kind','state','act','x','y','ang','head','target','speed','tier','mode','goalKey','chaseBlind','hEye']);const snap=e.sp.snap(e);r.look=snap.lh??snap.h;r.reason=pick(e.dbg,['hWhy','pursuit','why','search','retarget']);r.commit=pick(e.commit,['pid','variant','t','dur','until']);r.evidence={winner:e.evidence?.winner??null,identities:[...e.mem.p.values()].sort((a,b)=>a.id-b.id).map(q=>({id:q.id,seen:q.seen,confidence:q.conf,positionBelief:[q.lkx,q.lky],observedVelocity:[q.lvx,q.lvy],evidence:(q.ev||[]).map(v=>pick(v,['k','x','y','u','c','t']))})),anonymous:e.mem.leads.map(q=>pick(q,['id','pid','k','x','y','u','c','t'])),sounds:e.mem.sounds.map(q=>pick(q,['id','pid','attribution','type','x','y','u','c','t']))};r.search=e.search?{...pick(e.search,['phase','legs','maxLegs','until','why','pause','routeStage','lookAng','lkp','hd','sp']),goal:pick(e.search.goal,['x','y','k','a']),visited:e.search.visited}:null;r.route={goal:e.goal,path:e.path.slice(0,6).map(p=>({x:p.x,y:p.y,c:p.c,link:p.link?{to:p.link.to,propId:p.link.prop?.id}:null})),waypoints:e.path.length,nav:pick(e.nav,['plans','direct','recover','why'])};return r;}
H.World=function(seed,opts){clockTick=0;const w=Original(seed,opts),step=w.step;const ordinal=++worldN;let tick=0,chosen=null;w.step=function(){if(chosen===null&&w.eng.entities.length&&active){chosen=tracked<(active.sampleWorldLimit||2);tracked++;if(chosen)active.worlds.push({world:ordinal,seed});}clockTick=tick;const result=step();tick++;clockTick=tick;if(chosen&&active){assert(tick<=7200,'bounded trace length exceeded');active.records.push(clean({world:ordinal,tick,entities:w.eng.entities.map(entity).sort((a,b)=>a.id-b.id),events:[]}));}
 // Track event cursor outside runtime event objects.
 if(chosen&&active){const rec=active.records.at(-1);rec.events=w.evLog.slice(w.__stageAEventCursor||0).map(v=>pick(v,['t','pid','eid','kind','variant','ph','why']));w.__stageAEventCursor=w.evLog.length;}
 return result;};return w;};
const selections=[['s_hound2e.js',['2E H1 ','2E/HQA H14 ','2E H6 ','2E H10 ','2E/HQA H18 ','2E H3 ','2E H7 ','2E H15 ','2E H5 ']],['s_smiler.js',['SM01 ','SM03 ','SM04 ','SM05 ','SM08 ']],['s_evidence.js',['E4 ','E5 ','E6 ','E7 ']],['s_shared2f.js',['2F F01 ','2F F04 ','2F F09 ','2F F20 ']]];
const index=[];
for(const [file,prefixes] of selections){const cases=require('../tests/'+file);for(const prefix of prefixes){const c=cases.find(s=>s.name.startsWith(prefix));assert(c,file+' '+prefix);worldN=tracked=0;active=make(c.name,null,'dev/tests/'+file,{fixture:'Existing unmodified scenario function',prefix},['At most the first two stepped entity worlds are retained; every tick of those worlds is stored. The original scenario still runs all of its seeds/assertions.','Existing fixtures may set near LOD, seed memory/admin positions, or hold a motor for sensor-only isolation as documented in the source.','RNG streams are closures with no exposed checkpoint; not inspected or advanced by the observer.','Safe semantic AI state only: beliefs/observations, never hidden true player coordinates.']);active.worlds=[];active.sampleWorldLimit=prefix==='SM01 '?16:2;try{active.assertionResult=c.fn();}catch(e){active.assertionResult={ok:false,error:e.message};}if(prefix==='SM01 '){let keep=null;for(let i=0;i+1<active.worlds.length;i+=2){const a=active.worlds[i].world,b=active.worlds[i+1].world;if(active.records.some(r=>r.world===a&&r.entities.some(e=>['PROVOKED','ATTACKING'].includes(e.state)))&&active.records.some(r=>r.world===b&&r.entities.some(e=>e.state==='WATCHING'))){keep=[a,b];break;}}assert(keep,'representative lit chase and dark watch pair');active.records=active.records.filter(r=>keep.includes(r.world));active.worlds=active.worlds.filter(w=>keep.includes(w.world));active.limitations[0]='SM01 retains the first seed pair that actually reaches lit PROVOKED/ATTACKING and dark WATCHING, chosen after the unmodified scenario finishes. All original assertions still run.';}delete active.sampleWorldLimit;assert(active.records.length>0,'empty trace '+c.name);const name='ai-'+file.replace('.js','')+'-'+prefix.trim().replace(/[^a-zA-Z0-9]+/g,'-');index.push(save(out,name,active));console.log(name,active.records.length,'records','existing assertion',active.assertionResult.ok);active=null;}}
fs.writeFileSync(path.join(out,'ai-index.json'),JSON.stringify(index,null,2)+'\n');
