'use strict';
const assert=require('assert'),path=require('path'),{root,make,save,clean,hash}=require('./trace_io');
const {World,WORLD}=require('../harness'),{makeMover}=require('../move_model'),timing=require(path.join(root,'timing_policy.js'));
const out=path.resolve(process.argv[2]||path.join(__dirname,'traces'));Date.now=()=>0;
const scenarios=[['idle',120],['walk',180],['sprint',180],['acceleration-deceleration',180],['crouch',120],['crawl',60],['slide',180],['exhaustion',960],['recovery',240],['recovery-threshold',30],['vault',180],['deep-carpet',180]];
function frames(fps,N){const end=N/60*1000,arr=[],pattern=[1/240,1/90,1/165,1/48,1/120,1/75];let prev=0,k=0;while(prev<end){const next=fps==='jitter'?Math.min(end,prev+pattern[k++%pattern.length]*1000):Math.min(end,++k*1000/fps);if(next===prev)break;arr.push(timing.frameDelta(next,prev));prev=next;}return arr;}
function run(name,N,fps){const w=World(700),M=makeMover(w.sim,WORLD,()=>tick/60),H=M.H;let tick=0;H.x=4000;H.y=3504;let ix=1,iy=0;
 if(name==='crawl'){const p=WORLD.UNDER[0];H.x=p.cx;H.y=p.cy;ix=p.cross==='x'?1:0;iy=p.cross==='y'?1:0;}
 if(name==='vault'){const p=WORLD.LOW.find(p=>{const h=(p.cross==='x'?p.rect.w:p.rect.h)/2+65;return [-1,1].every(s=>w.ad.clear(p.cx+(p.cross==='x'?h*s:0),p.cy+(p.cross==='y'?h*s:0),15,'walk'));});assert(p,'vault fixture');const h=(p.cross==='x'?p.rect.w:p.rect.h)/2+65;H.x=p.cx-(p.cross==='x'?h:0);H.y=p.cy-(p.cross==='y'?h:0);ix=p.cross==='x'?1:0;iy=p.cross==='y'?1:0;}
 if(name==='deep-carpet'){const r=w.ad.rooms.find(r=>r.name==='DEEP CARPET');assert(r,'deep carpet room');let found=false;for(let y=(r.y+1)*96;y<(r.y+r.h-1)*96&&!found;y+=24)for(let x=(r.x+1)*96;x<(r.x+r.w-1)*96;x+=24)if(w.ad.clear(x,y,20,'walk')){H.x=x;H.y=y;found=true;break;}assert(found);}
 if(name==='recovery'||name==='recovery-threshold'){H.stamina=name==='recovery'?0:35.8;H.exhausted=true;}
 const T=make('motor/'+name,700,'move.js',{initial:clean(H),durationTicks:N,script:name},['Real move.js in existing headless adapter; no rendering, sockets or audio device. Crawl/slide posture is driven through documented makeMover input.']);let acc=0;
 for(const frame of frames(fps,N)){const r=timing.consume(acc,frame,dt=>{const k=tick;const moving=!['idle','recovery','recovery-threshold'].includes(name)&&!(name==='acceleration-deceleration'&&k>=60);const run=['sprint','exhaustion','slide','deep-carpet'].includes(name);const crouch=['crouch','crawl'].includes(name);const input=[moving?ix:0,moving?iy:0,run,crouch,k===60&&name==='slide'];M.step(input[0],input[1],run,crouch,dt,input[4]);const report=M.net();tick++;T.records.push({tick,input,x:H.x,y:H.y,vx:H.vx,vy:H.vy,stamina:H.stamina,exhausted:H.exhausted,state:M.mv.s,surface:M.mv.surf,distance:H.distance,events:report.ev,vault:M.mv.vault?{quality:M.mv.vault.quality,progress:M.mv.vault.t/M.mv.vault.dur}:null});});acc=r.accumulator;}
 assert.equal(tick,N);return T;
}
const index=[];
for(const [name,N] of scenarios){const ref=run(name,N,60),signature=hash(JSON.stringify(clean(ref.records))),schedule=[];for(const fps of [15,30,60,120,144,240,360,'jitter']){const T=run(name,N,fps),h=hash(JSON.stringify(clean(T.records)));assert.equal(h,signature,name+' @ '+fps);schedule.push({fps,ticks:T.records.length,recordsSha256:h,final:T.records.at(-1)});}ref.schedules=schedule;ref.observedStates=[...new Set(ref.records.map(r=>r.state))];if(name==='deep-carpet')assert(ref.records.some(r=>r.surface==='deep'));if(name==='crawl')assert(ref.observedStates.includes('crawl'));if(name==='vault')assert(ref.observedStates.includes('vault'));if(name==='slide')assert(ref.observedStates.includes('slide'));if(name==='exhaustion')assert(ref.records.some(r=>r.exhausted));if(name==='recovery-threshold'){assert(ref.records[0].exhausted);assert(ref.records.some(r=>!r.exhausted&&r.stamina>=36));}index.push(save(out,'motor-'+name,ref));console.log(name,ref.observedStates.join(','),N,'ticks x 8 schedules identical');}
require('fs').writeFileSync(path.join(out,'motor-index.json'),JSON.stringify(index,null,2)+'\n');
