'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),zlib=require('zlib'),assert=require('assert'),{spawnSync}=require('child_process'),{root,hash}=require('./trace_io');
const manifest=require('../baselines/v23.3.6-manifest.json'),traceDir=path.join(__dirname,'traces');let checks=0;
function check(name,fn){fn();checks++;console.log('PASS '+name);}
function run(file,args=[]){const r=spawnSync(process.execPath,[path.join(root,file),...args],{cwd:root,encoding:'utf8',timeout:120000});assert.ifError(r.error);assert.equal(r.status,0,r.stdout+'\n'+r.stderr);return r.stdout;}
check('227 immutable original files',()=>{assert.equal(manifest.files.length,227);for(const f of manifest.files){const b=fs.readFileSync(path.join(root,f.path));assert.equal(b.length,f.bytes,f.path);assert.equal(hash(b),f.sha256,f.path);}});
check('data schema and identity negative controls',()=>process.stdout.write(run('dev/stage_a/contracts_test.js')));
check('redirect and new JS syntax',()=>{const files=['redirect.js','server.js'];function visit(dir){for(const d of fs.readdirSync(path.join(root,dir),{withFileTypes:true})){const p=path.join(dir,d.name);if(d.isDirectory())visit(p);else if(p.endsWith('.js'))files.push(p);}}visit('dev/stage_a');visit('dev/contracts');visit('dev/fixtures');for(const f of files){const r=spawnSync(process.execPath,['--check',path.join(root,f)],{encoding:'utf8'});assert.ifError(r.error);assert.equal(r.status,0,f+' '+r.stderr);}});
const matrix=require('./future_matrix.json');
check('Z01–Z32 covered, future entry points refuse pass',()=>{assert.equal(matrix.length,32);assert.equal(new Set(matrix.map(x=>x.id)).size,32);let n=0;for(const g of new Set(matrix.map(x=>x.entry))){const r=spawnSync(process.execPath,[path.join(root,'dev/tests',g+'.js')],{encoding:'utf8'});assert.ifError(r.error);assert.equal(r.status,2,g);n+=(r.stdout.match(/NOT IMPLEMENTED/g)||[]).length;}assert.equal(n,32);});
let index=[];for(const group of ['motor','ai','death','navigation','network'])index.push(...JSON.parse(fs.readFileSync(path.join(traceDir,group+'-index.json'))));
check('trace hashes and bounded nonempty records',()=>{for(const i of index){const b=fs.readFileSync(path.join(traceDir,i.name+'.json.gz')),raw=zlib.gunzipSync(b),v=JSON.parse(raw);assert.equal(hash(b),i.sha256,i.name);assert.equal(hash(raw),i.semanticSha256,i.name);assert.equal(v.records.length,i.records);assert(v.records.length>0&&v.records.length<=20000);assert.equal(v.baselineSha256,manifest.sourceZipSha256);assert.equal(v.sourceSha256,hash(fs.readFileSync(path.join(root,v.source))));assert(v.records.every(r=>Number.isInteger(r.tick)));}});
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'tfb-stage-a-'));
try{
 check('diff helper finds first divergent tick and field',()=>{const a={records:[{tick:1,x:0},{tick:2,x:1}]},b={records:[{tick:1,x:0},{tick:2,x:2}]};const ap=path.join(temp,'a.json'),bp=path.join(temp,'b.json');fs.writeFileSync(ap,JSON.stringify(a));fs.writeFileSync(bp,JSON.stringify(b));const r=spawnSync(process.execPath,[path.join(__dirname,'diff_traces.js'),ap,bp],{encoding:'utf8'});assert.ifError(r.error);assert.equal(r.status,1);const j=JSON.parse(r.stdout);assert.equal(j.status,'FIRST DIVERGENT TICK');assert.equal(j.tick,2);assert.equal(j.fields[0].field,'record.x');run('dev/stage_a/diff_traces.js',[ap,ap]);});
 if(process.argv.includes('--regenerate'))check('fresh-process exact trace reproduction',()=>{for(const group of ['motor','ai','death','navigation','network']){console.log('CAPTURE '+group);run('dev/stage_a/capture_'+group+'.js',[temp]);}for(const i of index)assert.equal(hash(fs.readFileSync(path.join(temp,i.name+'.json.gz'))),i.sha256,i.name+' changed');});
}finally{fs.rmSync(temp,{recursive:true,force:true});}
console.log(JSON.stringify({result:'PASS',checks,traces:index.length,records:index.reduce((s,x)=>s+x.records,0),originalFilesUnchanged:227,futurePhysics:'NOT IMPLEMENTED BY DESIGN',legacySuiteFailures:'see baseline ledger',browser:'BLOCKED'}));
