'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),G=require('../../world_geometry'),M=require('../../world_motion');
process.env.ADMIN_PASSCODE=require('crypto').randomBytes(24).toString('hex');
const {server,launch,open,pixels,diagnostics}=require('../stage_h/browser_support');
const out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});
async function difference(page,id){return page.evaluate(id=>{__spatial.render(true);const s=__spatial,p=s.pass,opts=s.state.renderOptions;p.render(opts);const a=p.pixels();p.render({...opts,actors:opts.actors.filter(q=>q.id!==id&&q.owner!==id)});const b=p.pixels();let changed=0;for(let i=0;i<a.length;i+=4)if(a[i]!==b[i]||a[i+1]!==b[i+1]||a[i+2]!==b[i+2])changed++;p.render(opts);return{changed,error:p.gl.getError(),packet:opts.actors.find(q=>q.id===id)};},id);}
(async()=>{const d=require('../../levels/level0_spatial.json'),g=G.compile(d),s=await server(d),checks=[];let browser,a,b;const save=()=>fs.writeFileSync(path.join(out,'checks-raw.json'),JSON.stringify(checks,null,2));
try{browser=await launch();a=await open(browser,s,'Production A');await a.command({c:'freeze',on:1});await a.page.locator('#stQuality').selectOption('0.5',{force:true});b=await open(browser,s,'Production B');await b.page.locator('#stQuality').selectOption('0.5',{force:true});
const tp=async(c,p)=>{const q=g.supports(M.PROFILES.stand,p,[p.z-.01,p.z+.01])[0];assert(q,JSON.stringify(p));await c.teleport({...p,support:q.id});};
const ready=async c=>{await c.page.waitForFunction(()=>Math.hypot(__spatial.state.last.camera.x-__api.H.x,__spatial.state.last.camera.y-__api.H.y,__spatial.state.last.camera.z-__api.H.z)<.2&&__spatial.state.last.cutaway.groups.filter(g=>g.target).every(g=>g.fade===1),null,{timeout:30000});};
await tp(a,{x:6192,y:864,z:0});await tp(b,{x:6192,y:864,z:180});await ready(a);await ready(b);const aid=await a.page.evaluate(()=>__api.H.id),bid=await b.page.evaluate(()=>__api.H.id);
await a.page.waitForFunction(id=>__spatial.state.packets.some(p=>p.id==='p'+id&&p.z>179),bid);await b.page.waitForFunction(id=>__spatial.state.packets.some(p=>p.id==='p'+id&&p.z<1),aid);
const masks=[await difference(a.page,'p'+bid),await difference(b.page,'p'+aid)],states=[await a.inspect(),await b.inspect()];checks.push({name:'same XY separate floors, independent cutaway and peer masks',masks,states});save();assert(masks.every(m=>m.packet&&m.changed===0&&m.error===0));assert.equal(states[0].world.contentHash,states[1].world.contentHash);assert.equal(states[0].network.world.worldEpoch,states[1].network.world.worldEpoch);assert.equal(states[0].cutaway.groups.find(g=>g.id==='view:long-room:upper-slab').fade,1);assert.equal(states[1].cutaway.groups.find(g=>g.id==='view:long-room:upper-slab').fade,0);await a.page.screenshot({path:path.join(out,'same-xy-base.png')});await b.page.screenshot({path:path.join(out,'same-xy-upper.png')});
// Actual peer input across the retained rim; authority owns the unsupported arc.
await tp(a,{x:936,y:5520,z:0});await tp(b,{x:936,y:5568,z:0});await a.page.evaluate(id=>{window.__fallHistory=[];window.__fallTimer=setInterval(()=>{const p=__spatial.sample('p'+id);if(p)__fallHistory.push(p);},20);},bid);await b.page.keyboard.down('a');try{await b.page.waitForFunction(()=>__api.H.x<750&&__api.H.z< -95,null,{timeout:90000});}finally{await b.page.keyboard.up('a');}await b.page.waitForFunction(()=>Math.abs(__api.H.vx)<.1);const fall=await a.page.evaluate(()=>{clearInterval(__fallTimer);return __fallHistory;});checks.push({name:'two real clients observe authoritative lower fall',fall,state:await b.inspect()});save();assert(fall.some(p=>p.z< -90)&&fall.some(p=>p.mode==='airborne'||p.motionMode==='airborne'));await b.page.screenshot({path:path.join(out,'peer-lower-fall.png')});
const epoch=(await a.inspect()).network.world.worldEpoch;await b.context.close();b=await open(browser,s,'Production reconnect');await b.page.locator('#stQuality').selectOption('0.5',{force:true});const reconnect=await b.inspect();checks.push({name:'real reconnect preserves world and receives production anchors',state:reconnect});save();assert.equal(reconnect.network.world.worldEpoch,epoch);
// Walk over the server-selected device; use its replicated XYZ/support only.
const item=await a.page.evaluate(()=>__items[0]);assert(item&&Number.isFinite(item[3]));const offsets=[[-96,0],[96,0],[0,-96],[0,96]],offset=offsets.find(([x,y])=>{const p={x:item[0]+x,y:item[1]+y,z:item[3]};return g.clearance(M.PROFILES.stand,p).fits&&g.supports(M.PROFILES.stand,p,[p.z,p.z]).length&&!g.sweep(M.PROFILES.stand,p,{x:-x,y:-y,z:0});});assert(offset,'item approach');await tp(a,{x:item[0]+offset[0],y:item[1]+offset[1],z:item[3]});await ready(a);await a.page.waitForFunction(id=>__spatial.state.packets.some(p=>p.id==='objective:'+id),item[5]);const itemPixels=await difference(a.page,'objective:'+item[5]);checks.push({name:'physical cartograph art visible',item,itemPixels});save();assert(itemPixels.changed>0);await a.page.screenshot({path:path.join(out,'cartograph.png')});const key=offset[0]?(offset[0]<0?'d':'a'):(offset[1]<0?'s':'w');await a.page.keyboard.down(key);try{await a.page.waitForFunction(()=>__inv.has('cartograph'),null,{timeout:30000});}finally{await a.page.keyboard.up(key);}await b.page.waitForFunction(()=>__items.length===0);checks.push({name:'one cartograph collected through normal proximity protocol, removed for peer',inventory:await a.page.evaluate(()=>__inv.items)});save();
const selectedExits=await a.page.evaluate(()=>__glitches);let exit,approach,exitOffset;for(const e of selectedExits){for(const [dx,dy]of [[120,0],[-120,0],[0,120],[0,-120]]){const p={x:e[0]+dx,y:e[1]+dy,z:e[4]};if(g.clearance(M.PROFILES.stand,p).fits&&g.supports(M.PROFILES.stand,p,[p.z,p.z]).length&&!g.sweep(M.PROFILES.stand,p,{x:-dx,y:-dy,z:0})){exit=e;approach=p;exitOffset=[dx,dy];break;}}if(exit)break;}assert(exit,'a physical approach to a selected wall');await tp(a,approach);await ready(a);await a.page.waitForFunction(id=>__spatial.state.packets.some(p=>p.id==='objective:'+id),exit[6]);const exitPixels=await difference(a.page,'objective:'+exit[6]);checks.push({name:'selected real wall effect visible',exit,exitPixels});save();assert(exitPixels.changed>0);await a.page.screenshot({path:path.join(out,'glitched-wall.png')});const exitKey=exitOffset[0]?(exitOffset[0]<0?'d':'a'):(exitOffset[1]<0?'s':'w');await a.page.keyboard.down(exitKey);try{await a.page.waitForFunction(()=>document.body.classList.contains('gl-out')||__messages.some(m=>m.t==='exit'),null,{timeout:30000});}finally{await a.page.keyboard.up(exitKey);}checks.push({name:'normal glitched-wall escape loop',messages:await a.page.evaluate(()=>__messages.filter(m=>m.t==='exit'))});save();
a.validate();b.validate();fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',browser:browser.version(),checks:checks.map(c=>c.name),errors:[a.errors,b.errors],console:[a.consoleErrors,b.consoleErrors],server:s.log},null,2));console.log('PASS production multiplayer, same-XY, fall, reconnect, cartograph and exit');
}catch(e){save();for(const [id,c]of [['a',a],['b',b]])if(c){await c.page.screenshot({path:path.join(out,id+'-failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,id+'-diagnostic.json'),JSON.stringify(await diagnostics(c).catch(()=>null),null,2));}fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),stack:e.stack,server:s.log},null,2));throw e;}finally{if(browser)await browser.close();await s.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
