'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),G=require('../../world_geometry'),M=require('../../world_motion');
process.env.ADMIN_PASSCODE=require('crypto').randomBytes(24).toString('hex');
const {server,launch,open,pixels,diagnostics}=require('../stage_h/browser_support');
const out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});
(async()=>{const d=require('../../levels/level0_spatial.json'),g=G.compile(d),s=await server(d),rows=[];let browser,a;const save=()=>fs.writeFileSync(path.join(out,'readability-raw.json'),JSON.stringify(rows,null,2));
try{browser=await launch();a=await open(browser,s,'Level 0 readability');await a.command({c:'freeze',on:1});await a.page.evaluate(()=>{__api.gear.eq.kind='lantern';__api.H.equipment.kind='lantern';__spatial.config.labels=false;__ents.dbgCfg.on=false;});
const tp=async p=>{const support=g.supports(M.PROFILES.stand,p,[p.z-.01,p.z+.01])[0];assert(support,JSON.stringify(p));await a.teleport({...p,support:support.id});};
const ready=()=>a.page.waitForFunction(()=>Math.hypot(__spatial.state.last.camera.x-__api.H.x,__spatial.state.last.camera.y-__api.H.y,__spatial.state.last.camera.z-__api.H.z)<.2&&__spatial.state.last.cutaway.groups.every(g=>g.fade===(g.target?1:0)),null,{timeout:40000});
const capture=async(name,quality=1)=>{await a.page.evaluate(q=>__spatial.config.quality=q,quality);await ready();const start=performance.now(),pix=await pixels(a.page),state=await a.inspect(),row={name,quality,completedRoundTripMs:performance.now()-start,pixels:pix,state};rows.push(row);save();assert(pix.lit>1000&&pix.error===0,name);assert.equal(state.last.occluders,d.solids.length);assert(state.last.cutaway.groups.filter(g=>g.target).length<d.viewGroups.length);await a.page.screenshot({path:path.join(out,name+'.png')});return row;};
const exits=await a.page.evaluate(()=>__glitches);
for(const room of d.production.rooms){const center={x:(room.x+room.w/2)*96,y:(room.y+room.h/2)*96},pool=d.anchors.filter(a=>a.kind==='hound-spawn'&&a.position.z===0&&a.position.x>room.x*96&&a.position.x<(room.x+room.w)*96&&a.position.y>room.y*96&&a.position.y<(room.y+room.h)*96&&exits.every(e=>Math.hypot(a.position.x-e[0],a.position.y-e[1])>120));pool.sort((a,b)=>Math.hypot(a.position.x-center.x,a.position.y-center.y)-Math.hypot(b.position.x-center.x,b.position.y-center.y));assert(pool.length);await tp(room.code==='06'?{x:7056,y:1104,z:0}:pool[0].position);await capture('room-'+room.code);}
for(const [name,p]of [['stairs-base',{x:5616,y:1512,z:0}],['stairs-mid',{x:5616,y:1244,z:108}],['stairs-upper',{x:5616,y:951,z:180}],['ramp-mid',{x:6432,y:1248,z:95.625}],['ramp-upper',{x:6432,y:960,z:180}],['lower',{x:720,y:5568,z:-96}]]){await tp(p);await capture(name);}
await tp({x:1584,y:864,z:0});await a.page.keyboard.press('c');await a.page.keyboard.down('d');try{await a.page.waitForFunction(()=>__api.H.x>1768,null,{timeout:30000});}finally{await a.page.keyboard.up('d');}await a.page.waitForFunction(()=>Math.abs(__api.H.vx)<.1);await capture('crawl-interior');
await tp({x:7056,y:1104,z:0});await a.page.keyboard.press('c');const qualityRows=[];for(const q of [1,.5]){await a.page.evaluate(v=>__spatial.config.quality=v,q);await ready();const samples=[];for(let i=0;i<5;i++){const start=performance.now(),pix=await pixels(a.page);samples.push({completedRoundTripMs:performance.now()-start,pix});assert(pix.lit>1000&&pix.error===0);}qualityRows.push({quality:q,samples,state:await a.inspect()});save();}rows.push({name:'full-reduced-truth-and-performance',qualityRows});save();const A=qualityRows[0].state,B=qualityRows[1].state;assert.deepEqual(A.last.submittedCandidateIds,B.last.submittedCandidateIds);assert.deepEqual(A.world,B.world);for(const k of ['x','y','z','support','generation'])assert.equal(A.network.pose[k],B.network.pose[k]);assert(A.last.occluderBatches>1);assert.equal(A.last.lightCount,B.last.lightCount);assert.equal(A.last.target.width,B.last.target.width*2);
const layers=await a.page.evaluate(()=>({labels:__spatial.state.packets.filter(p=>p.kind==='label').length,legacy:Object.fromEntries(['mp','light','peerTip','aiDebug','glitchFx'].map(id=>[id,document.getElementById(id)?getComputedStyle(document.getElementById(id)).display:'absent']))}));assert.equal(layers.labels,0);assert(Object.values(layers.legacy).every(v=>v==='none'||v==='absent'));rows.push({name:'no-debug-labels-or-unmasked-legacy-world-layers',layers});save();a.validate();fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',hash:d.contentHash,browser:browser.version(),gpu:A.gpu,rooms:12,featureCaptures:7,qualityRows,layers,errors:a.errors,console:a.consoleErrors,externalFailures:a.failed,server:s.log},null,2));console.log('PASS 12 rooms, 7 vertical captures, complete geometry, local cutaway, full/reduced truth, measured GPU');
}catch(e){save();if(a){await a.page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'diagnostic.json'),JSON.stringify(await diagnostics(a),null,2));}fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),stack:e.stack,server:s.log},null,2));throw e;}finally{if(browser)await browser.close();await s.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
