'use strict';
const fs=require('fs'),assert=require('assert'),G=require('../../world_geometry'),V=require('../../world_view'),M=require('../../world_motion'),create=require('../../sim'),{build}=require('../../levels/level0_spatial'),{summary,host}=require('../stage_i/metrics');
const out=process.argv[2],rows=[],timed=fn=>{const t=performance.now(),value=fn();return {ms:performance.now()-t,value};};
const built=timed(build),d=built.value,compiled=timed(()=>G.compile(d)),g=compiled.value,view=timed(()=>V.compile(d));rows.push({workload:'full production build and immutable compile',buildMs:built.ms,geometryCompileMs:compiled.ms,viewCompileMs:view.ms,solids:d.solids.length,supports:d.supportPatches.length,chunks:Object.keys(view.value.chunks).length});
const poses=d.anchors.filter(a=>a.kind==='hound-spawn'),query=[],ray=[];for(let i=0;i<2000;i++){const a=poses[i%poses.length].position,t=performance.now();assert(g.clearance(M.ENTITY_PROFILES.hound,a).fits);assert(g.supports(M.ENTITY_PROFILES.hound,a,[a.z-.001,a.z+.001]).length);query.push(performance.now()-t);const start=performance.now();g.raycast({...a,z:a.z+28},{x:a.x+300,y:a.y+150,z:a.z+28},'visible');ray.push(performance.now()-start);}rows.push({workload:'distributed physical queries',queries:2000,supportAndClearanceMs:summary(query),rayMs:summary(ray)});
function save(){fs.writeFileSync(out,JSON.stringify({status:'PASS',classification:'BOUNDED MEASUREMENT — no Part 3G or hardware performance certification',host:host(),hash:d.contentHash,rows},null,2)+'\n');}save();
for(const count of [1,8]){const made=timed(()=>create({world:d,seed:731,director:true})),sim=made.value;for(let i=0;i<count;i++){const p=sim.addPlayer(i+1);sim.join(p);if(i){const at=poses[(i*23)%poses.length].position;sim.spatialMotion.initialize(Object.assign(p,at));p.navSurfaceId=g.supportPatch(p.supportId)?.navSurfaceId;}p.light=true;}
 const ticks=[],payload=[];let deaths=0;for(let i=0;i<1200;i++){const t=performance.now();sim.step(1/60);ticks.push(performance.now()-t);for(const e of sim.engine.entities){assert([e.x,e.y,e.z].every(Number.isFinite));assert(g.clearance(e.shape,e).fits);}if(i%60===0)payload.push(Buffer.byteLength(JSON.stringify(sim.entities())));deaths=sim.players.filter(p=>p.dead).length;}
 rows.push({workload:'normal production director and complete physical world',players:count,entities:sim.engine.entities.length,deaths,ticks:1200,simulatedSeconds:20,createMs:made.ms,allTickMs:summary(ticks),postFirstSecondTickMs:summary(ticks.slice(60)),entitySnapshotBytes:summary(payload),navigation:sim.engine.geo.navStats,senses:sim.engine.geo.sensorStats,memory:process.memoryUsage(),diagnostics:sim.engine.entities.flatMap(e=>e.diagnostics||[])});assert(rows.at(-1).diagnostics.length===0);save();
}console.log(JSON.stringify({status:'PASS',rows:rows.length,hash:d.contentHash}));
