'use strict';
const assert=require('assert'),fs=require('fs'),{internalAI,player}=require('../stage_e/test_helpers'),M=require('../../world_motion'),create=require('../../sim');
const d=require('../../levels/level0_spatial.json'),sim=create({world:d,seed:83,director:false}),AI=internalAI(),eng=AI.create({adapter:sim.adapter,seed:408}),e=eng.spawn('hound',6192,864,{z:0});e.ang=Math.PI;
const checks=[],details={},out=process.argv[2];const save=()=>{if(out)fs.writeFileSync(out,JSON.stringify({status:checks.every(c=>c.ok)?'PASS':'FAIL',checks,details},null,2)+'\n');};
function test(name,fn){try{fn();checks.push({name,ok:true});console.log('PASS '+name);}catch(e){checks.push({name,ok:false,error:e.stack});console.error('FAIL '+name,e.message);}save();}
test('production visual memory consumes observations, not hidden velocity or support',()=>{const p=player({x:6120,y:864,z:0});for(const k of ['vx','vy','vz','supportId','route','destination'])Object.defineProperty(p,k,{get(){throw Error('forbidden visual truth '+k);}});assert(eng.geo.visibleBody(e,p).visible);eng.now=.1;AI.updateVision(e,eng,.1,[p]);const r=e.mem.p.get(1);assert(r?.seen);assert.equal(r.lvx,0);assert(r.spatial.supportCandidates.includes('nav:base'));const before=JSON.stringify({v:r.visual,s:r.spatial,lkz:r.lkz,lkx:r.lkx});eng.now=.3;AI.updateVision(e,eng,.1,[player({x:6120,y:864,z:180,supportId:'SECRET',vx:999,route:['SECRET']})]);assert(!r.seen);assert.equal(JSON.stringify({v:r.visual,s:r.spatial,lkz:r.lkz,lkx:r.lkx}),before);details.memory=JSON.parse(before);});
test('upper impact produces bounded ambiguous hearing without hidden identity',()=>{const h=eng.spawn('hound',6192,864,{z:0}),p=player({x:6192,y:864,z:180});eng.setPlayers([p]);const q=AI.hearEvent(h,eng,{x:p.x,y:p.y,z:p.z,r:5000,I:2,type:'impact',src:999,supportId:'SECRET',route:['SECRET'],vx:900});assert(q);assert.equal(q.pid,null);assert.equal(h.mem.p.size,0);assert(h.mem.leads[0].zMin<=0&&h.mem.leads[0].zMax>=180);assert(!JSON.stringify(q).includes('SECRET'));assert.equal(q.z,undefined);details.hearing=q;});
test('production slab masks all visible and IR rays and prevents cross-floor capture',()=>{const p=player({x:6192,y:864,z:180,light:true}),base=eng.geo.lightAt(e,[]);for(const channel of ['visible','ir','collision'])assert(eng.geo.geometry.raycast(eng.geo.eye(e),eng.geo.eye(p),channel));assert(!eng.geo.physicalContact(e,p,500));eng.setPlayers([p]);assert.equal(AI.beginCapture(eng,e,p,{}),null);assert.equal(eng.geo.lightAt(e,[p]),base);assert.equal(eng.geo.lightAt(e,[{...p,z:0,kind:'camcorder',ir:1,irPower:100}]),base);});
if(checks.some(c=>!c.ok))process.exitCode=1;
