'use strict';
const assert=require('assert'),fs=require('fs'),G=require('../../world_geometry'),M=require('../../world_motion'),AI=require('../../ai'),create=require('../../sim'),{mover}=require('../stage_c/helpers');
const out=process.argv[2],d=require('../../levels/level0_spatial.json'),g=G.compile(d),results=[],details={};
function save(){if(out)fs.writeFileSync(out,JSON.stringify({status:results.some(r=>!r.ok)?'FAIL':'PASS',hash:d.contentHash,results,details},null,2)+'\n');}
function test(name,fn){try{fn();results.push({name,ok:true});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL '+name,e.message);}save();}
const byId=new Map(d.anchors.map(a=>[a.id,a])),spawn=d.anchors.find(a=>a.kind==='spawn').position;
test('all explicit anchors have full XYZ clearance and named physical support',()=>{for(const a of d.anchors){const p=d.colliderProfiles.find(p=>p.id===a.colliderProfileId);assert(g.clearance(p,a.position).fits,a.id);assert(g.supports(p,a.position,[a.position.z-.001,a.position.z+.001]).some(p=>p.id===a.supportId),a.id);}details.anchorCounts=d.anchors.reduce((o,a)=>(o[a.kind]=(o[a.kind]||0)+1,o),{});});
let s;
test('seeded production director, one cartograph, three variable exits',()=>{
 const run=()=>{const sim=create({world:d,seed:314159,director:false}),rows=[];s=sim;for(let n=0;n<100;n++){
  if(n)sim.resetWorld();const snap=sim.entities(),ents=sim.engine.entities;
  const hs=ents.filter(e=>e.kind==='hound').length,ss=ents.filter(e=>e.kind==='smiler').length;assert(hs>=1&&hs<=2);assert(ss>=2&&ss<=5);assert.equal(snap.it.length,1);assert.equal(snap.it[0][2],'cartograph');assert.equal(snap.gw.length,3);
  for(let i=0;i<ents.length;i++){const e=ents[i],a=byId.get(e.spawnAnchorId);assert(a);assert(Math.hypot(e.x-spawn.x,e.y-spawn.y,e.z-spawn.z)>=(e.kind==='hound'?3000:1700));assert(g.clearance(e.shape,e).fits);for(let j=0;j<i;j++)assert(Math.hypot(e.x-ents[j].x,e.y-ents[j].y,e.z-ents[j].z)>=(e.kind==='hound'?1500:1100));}
  for(let i=0;i<3;i++){const a=byId.get(snap.gw[i][6]);assert(a.baseReachable);for(let j=0;j<i;j++)assert(Math.hypot(snap.gw[i][0]-snap.gw[j][0],snap.gw[i][1]-snap.gw[j][1])>=2600);assert(Math.hypot(snap.it[0][0]-snap.gw[i][0],snap.it[0][1]-snap.gw[i][1])>=700);}
  rows.push({entities:ents.map(e=>e.spawnAnchorId),item:snap.it[0][5],exits:snap.gw.map(a=>a[6])});
 }return rows;};const a=run(),b=run();details.selection=a;assert.deepEqual(a,b);assert(new Set(a.map(r=>r.item)).size>20);assert(new Set(a.map(r=>r.exits.join('|'))).size>20);assert(a.some(r=>r.entities.some(id=>byId.get(id).position.z===180)));assert(a.some(r=>r.entities.some(id=>byId.get(id).position.z===-96)));details.selectionWorlds=100;
});
test('cartograph collection and escape require correct elevation and physical ray',()=>{const p=s.addPlayer('objective');s.join(p);s.admin.freeze(true);const item=s.admin.nearestItem(p.x,p.y),exit=s.glitches[0];Object.assign(p,{x:item.x,y:item.y,z:180});assert.equal(s.takeItem(p),null);Object.assign(p,item);assert.equal(s.takeItem(p),'cartograph');assert.equal(s.takeItem(p),null);Object.assign(p,{x:exit.x,y:exit.y,z:180,active:true,exited:false});s.step(1/60);assert(!p.exited);Object.assign(p,{z:exit.z});s.step(1/60);assert(p.exited);details.objective={item,exit};});
test('existing props retain swept player vault and crawl meanings',()=>{
 for(const prop of d.production.lowObstacles){const axis=prop.cross,a={x:prop.cx,y:prop.cy,z:0};a[axis]=prop.rect[axis]-80;const m=mover(d,a,d.production.lowObstacles);let vault=false;for(let i=0;i<120;i++){m.step(axis==='x'?1:0,axis==='y'?1:0,true);vault ||= m.mv.s==='vault';assert(g.clearance(m.H.shape,m.H).fits);}assert(vault,prop.id);assert(m.H[axis]>prop.rect[axis]+(axis==='x'?prop.rect.w:prop.rect.h),prop.id);}
 for(const gap of d.production.tightGapSurfaces){const n=d.navSurfaces.find(n=>n.id===gap.navSurfaceId);assert(!n.clearanceProfileIds.includes('profile:hound'));assert(!n.clearanceProfileIds.includes('profile:smiler'));const p=require('../../world').PROPS.find(p=>p.id===gap.propId),at={x:p.cx,y:p.cy,z:0};assert(g.clearance(M.PROFILES.crawl,at).fits);assert(!g.clearance(M.PROFILES.stand,at).fits);}
 for(const p of require('../../world').PROPS.filter(p=>p.type==='under')){assert(g.clearance(M.PROFILES.crouch,{x:p.cx,y:p.cy,z:0}).fits);assert(!g.clearance(M.PROFILES.stand,{x:p.cx,y:p.cy,z:0}).fits);}
});
test('same-XY spatial senses respect the slab and keep acoustic uncertainty',()=>{const geo=s.engine.geo,lo={x:6192,y:864,z:0,shape:M.ENTITY_PROFILES.hound},hi={...lo,z:180,shape:M.PROFILES.stand};assert(!geo.visibleBody(lo,hi).visible);assert(!geo.visibleBody(hi,lo).visible);assert(!geo.physicalContact(lo,hi,60));assert(!geo.clearRay(geo.eye(lo),geo.eye(hi),'ir'));const sound=g.propagateSound({x:hi.x,y:hi.y,z:hi.z+10},{x:lo.x,y:lo.y,z:lo.z+20});details.sound=sound;assert(sound.audible&&sound.observation.unresolved);assert(sound.observation.zMin<=0&&sound.observation.zMax>=180);for(const key of ['z','supportId','src','route'])assert(!(key in sound.observation));const fake={...hi,kind:'flashlight',light:true,angle:0,pitch:-Math.PI/2};assert.equal(geo.lightAt(lo,[fake]),geo.lightAt(lo,[]));});
if(results.some(r=>!r.ok))process.exitCode=1;else console.log(JSON.stringify({status:'PASS',checks:results.length}));
