'use strict';
const assert=require('assert'),fs=require('fs'),G=require('../../world_geometry'),V=require('../../world_view'),M=require('../../world_motion'),d=require('../../levels/level0_spatial.json'),g=G.compile(d),model=V.compile(d),rows=[];
// Independently brute-force every physical ray and compare the chunk candidate
// view oracle; all solids remain in simulation whatever the local camera sees.
const inside=(p,s)=>s.footprint.every((v,i)=>{const n=s.footprint[(i+1)%s.footprint.length];return (n.x-v.x)*(p.y-v.y)-(n.y-v.y)*(p.x-v.x)>=0;});
let rays=0,after64=0;const poses=d.anchors.filter(a=>a.kind==='hound-spawn');for(let n=0;n<poses.length;n++){const a=poses[n].position,eye={...a,z:a.z+28};for(const [dx,dy,dz]of [[300,0,0],[-300,0,0],[0,300,0],[0,-300,0],[0,0,180],[200,200,180]]){const to={x:a.x+dx,y:a.y+dy,z:eye.z+dz},all=model.solids.filter(s=>s.visible).some(s=>{const h=V.interval(s,eye,to,V.BOUNDARY);return h&&h.exit>1e-6&&h.enter<1;});assert.equal(V.visible(model,eye,to),!all);const hit=g.raycast(eye,to,'visible');if(hit&&model.solids.findIndex(s=>s.id===hit.primitiveId)>=64)after64++;rays++;}}
for(const a of poses){const scope=V.footprint(960,600,a.position),min={x:scope.minX,y:scope.minY,z:d.bounds.min.z},max={x:scope.maxX,y:scope.maxY,z:d.bounds.max.z};const lights=d.lights.filter(l=>Math.hypot(Math.max(min.x-l.position.x,0,l.position.x-max.x),Math.max(min.y-l.position.y,0,l.position.y-max.y))<=l.range);for(const l of lights)for(const k of ['x','y','z']){min[k]=Math.min(min[k],l.position[k]);max[k]=Math.max(max[k],l.position[k]);}const selected=V.candidates(model,min,max),expected=model.solids.filter(s=>['x','y','z'].every(k=>s.max[k]>=min[k]-V.BOUNDARY&&s.min[k]<=max[k]+V.BOUNDARY)).map(s=>s.index);assert.deepEqual(selected,expected);rows.push({anchor:a.id,candidates:selected.length,batches:Math.ceil(selected.length/64),lights:lights.length});}
for(const x of [768-V.BOUNDARY/2,1536-V.BOUNDARY/2,3072-V.BOUNDARY/2]){const min={x,y:0,z:d.bounds.min.z},max={x,y:6912,z:d.bounds.max.z},selected=V.candidates(model,min,max),expected=model.solids.filter(s=>['x','y','z'].every(k=>s.max[k]>=min[k]-V.BOUNDARY&&s.min[k]<=max[k]+V.BOUNDARY)).map(s=>s.index);assert.deepEqual(selected,expected,'conservative chunk boundary margin');}
const perm=JSON.parse(JSON.stringify(d));perm.solids.reverse();assert.deepEqual(V.compile(perm),model);assert(rows.some(r=>r.batches>1));assert.equal(g.definition.solids.length,d.solids.length);
const result={status:'PASS',hash:d.contentHash,physicalSolids:d.solids.length,completeModelSolids:model.solids.length,rayComparisons:rays,physicalHitsAfterGlobal64:after64,candidateHullsCompared:rows.length,maxCandidates:Math.max(...rows.map(r=>r.candidates)),maxBatches:Math.max(...rows.map(r=>r.batches)),rows};fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,rows:undefined}));
