'use strict';
const path=require('path'),fs=require('fs'),assert=require('assert'),{serve,launch}=require('./browser_support');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..')),out=path.resolve(process.argv[3]||path.join(__dirname,'evidence'));fs.mkdirSync(out,{recursive:true});
(async()=>{const server=await serve(root);let b;try{b=await launch();const p=await b.newPage({viewport:{width:1280,height:720}});await p.goto(server.url+'/stage_d.html?manual=1');await p.waitForFunction(()=>window.stageD?.ready);const results=[];
 for(const [width,height,quality]of [[1280,720,1],[1280,720,.5],[1920,1080,1],[1920,1080,.5]]){await p.setViewportSize({width,height});const r=await p.evaluate(async quality=>{const d=stageD,pass=d.views[0].pass,g=pass.gl,probe=new Uint8Array(4);d.setScene('stairs',{quality});
  const fence=()=>{g.bindFramebuffer(g.READ_FRAMEBUFFER,pass.fbo);g.readPixels(Math.floor(pass.target.width/2),Math.floor(pass.target.height/2),1,1,g.RGBA,g.UNSIGNED_BYTE,probe);};
  const frame=i=>{d.draw({quality,eye:{x:368+(i%3)*.2,y:440,z:182}});fence();};
  for(let i=0;i<3;i++)frame(i);const times=[];for(let i=0;i<16;i++){const t=performance.now();frame(i);times.push(performance.now()-t);}const s=times.slice().sort((a,b)=>a-b);
  const raf=[];let prev=null;await new Promise(resolve=>{function tick(t){if(prev!==null)raf.push(t-prev);prev=t;frame(raf.length);if(raf.length>=24)resolve();else requestAnimationFrame(tick);}requestAnimationFrame(tick);});const a=raf.slice().sort((x,y)=>x-y);
  return {pass:g.getError()===0,quality,metadata:d.metadata(),completedFrameWallMs:{method:'draw + 1x1 synchronous readPixels from the rendered color target; three warmups, sixteen samples; includes CPU, GPU and readback overhead, not isolated GPU time',samples:times,median:s[7],p95:s[14],max:s[15]},steadyRafMs:{method:'24 intervals, each frame drained by readback, no pre-existing submission backlog',samples:raf,median:a[11],p95:a[22],max:a[23]},heap:performance.memory?{used:performance.memory.usedJSHeapSize,total:performance.memory.totalJSHeapSize}:null};},quality);assert(r.pass);results.push(r);console.log('MEASURE '+width+'x'+height+' q='+quality+' fenced median='+r.completedFrameWallMs.median.toFixed(2)+' p95='+r.completedFrameWallMs.p95.toFixed(2));}
 const result={status:'MEASURED',browser:b.version(),results,metricCorrection:'The historical development/browser-extended-before-opaque-depth.json called draw+gl.finish samples synchronizedFrameWallMs. Those values measure enqueue CPU time on this Chromium setup, NOT completed GPU time. Its RAF samples also follow a burst queue. Neither is used to claim frame-budget acceptance. This file provides drained, readback-fenced measurements with eye movement and supersedes those initial performance numbers.',budget:'16.7 ms hardware reference target remains unverified; only the exposed SwiftShader software GPU was available. No visibility/geometry omitted for performance.'};fs.writeFileSync(path.join(out,'browser-performance.json'),JSON.stringify(result,null,2)+'\n');
 }finally{if(b)await b.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
