'use strict';
const path=require('path'),fs=require('fs'),assert=require('assert'),{serve,launch,get}=require('./browser_support');
const root=path.resolve(process.argv[2]||path.join(__dirname,'../..')),out=path.resolve(process.argv[3]||path.join(__dirname,'evidence'));fs.mkdirSync(out,{recursive:true});
(async()=>{const server=await serve(root);let browser;const errors=[],checks=[];try{
 browser=await launch();const page=await browser.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(String(e)));
 const bytes=[];for(const file of ['world_view.js','stage_d.html','assets/stageD-pixi.js','assets/stageD-browser.js','assets/stageD-prototype.js','assets/stageD-world.json']){const r=await get(server.port,'/'+file);assert.equal(r.status,200,file);assert(r.bytes.equals(fs.readFileSync(path.join(root,file))));bytes.push(file);}
 await page.goto(server.url+'/stage_d.html?manual=1');await page.waitForFunction(()=>window.stageD?.ready,{}, {timeout:20000});
 const run=async(name,fn)=>{const result=await page.evaluate(fn);assert(result.pass,name+' '+JSON.stringify(result));checks.push({name,...result});console.log('PASS '+name);};
 await run('lower observer: hidden upper actor AND last-drawn overlay cannot leak',()=>{const d=stageD;d.setScene('lower');const withActor=d.pixels();d.draw({exclude:['upper-same-xy'],overlays:['upper-same-xy']});const without=d.pixels();let changed=0;for(let i=0;i<withActor.length;i+=4)if(withActor[i]!==without[i]||withActor[i+1]!==without[i+1]||withActor[i+2]!==without[i+2])changed++;return {pass:changed===0,changedPixels:changed,fade:d.views[0].view.snapshot(),cpuVisible:TFB_VIEW.visible(d.model,{x:160,y:160,z:50},{x:160,y:160,z:210})};});
 await run('cutaway changes camera composition, never physical visibility',()=>{const d=stageD;d.setScene('lower',{cutaway:false});const a=d.digest(d.pixels());const ray=d.geometry.raycast({x:160,y:160,z:50},{x:160,y:160,z:210},'visible');d.draw({cutaway:true,settle:true});const b=d.digest(d.pixels()),after=d.geometry.raycast({x:160,y:160,z:50},{x:160,y:160,z:210},'visible');return {pass:a.hash!==b.hash&&JSON.stringify(ray)===JSON.stringify(after),opaque:a,cut:b,blocker:ray.primitiveId};});
 await run('unseen opaque roof writes black depth until eligible cutaway',()=>{const d=stageD;d.setScene('lower',{cutaway:false});const pass=d.views[0].pass,q=TFB_VIEW.project({x:160,y:160,z:30},pass.last.camera,pass.last.scope.scale),x=Math.floor((q.x+pass.width/2)*pass.target.width/pass.width),y=Math.floor((pass.height/2-q.y)*pass.target.height/pass.height),i=(y*pass.target.width+x)*4;const a=Array.from(d.pixels().slice(i,i+3));d.draw({cutaway:true,settle:true});const b=Array.from(d.pixels().slice(i,i+3));return {pass:a.every(v=>v===0)&&b.some(v=>v>0),opaquePixel:a,cutawayPixel:b};});
 await run('same physical snapshot: independent lower / upper view state',()=>{const d=stageD,h=d.worldHash(),s=d.snapshotHash(),m=d.pair(true);const sameWorld=d.views[0].view.model===d.views[1].view.model&&d.views[0].pass.model===d.views[1].pass.model;const a=d.digest(d.pixels(0)),b=d.digest(d.pixels(1));return {pass:sameWorld&&m[0].cutaway.groups[0].fade===1&&m[1].cutaway.groups[0].fade===0&&a.hash!==b.hash&&d.worldHash()===h&&d.snapshotHash()===s,sameWorld,hash:h,snapshotHash:s,views:m};});
 await run('first resized frame has geometry and no framebuffer sampler feedback',()=>{const d=stageD;const first=d.views.map(v=>d.digest(v.pass.pixels()));const errors=d.views.map(v=>v.pass.gl.getError());d.draw();const second=d.views.map(v=>d.digest(v.pass.pixels()));return {pass:errors.every(e=>e===0)&&first.every((v,i)=>v.hash===second[i].hash&&v.lit>1000),errors,first,second};});
 await page.locator('#controls').evaluate(e=>e.style.visibility='hidden');await page.screenshot({path:path.join(out,'core-two-views.png')});await page.evaluate(()=>stageD.pair(false));
 await run('upper observer: lower actor remains physically hidden',()=>{const d=stageD;d.setScene('upper');const a=d.digest(d.pixels());d.draw({exclude:['lower-local'],overlays:['lower-local']});const b=d.digest(d.pixels());return {pass:a.hash===b.hash,with:a,without:b};});
 await run('real stairwell: upper actor visible from lower-root stair pose',()=>{const d=stageD;d.setScene('stairs');const a=d.digest(d.pixels());d.draw({exclude:['upper-peer']});const b=d.digest(d.pixels());const blocked=d.geometry.raycast({x:368,y:440,z:182},{x:300,y:460,z:210},'visible');return {pass:a.hash!==b.hash&&!blocked,with:a,without:b,eyeZ:182,observerRootZ:132,targetRootZ:180};});
 for(const name of ['lower','upper','stairs','ramp','wall','crawl','balcony']){await page.evaluate(n=>stageD.setScene(n),name);await page.screenshot({path:path.join(out,'core-'+name+'.png')});}
 await run('front / partial / deeper partial occlusion by narrow wall',()=>{const d=stageD;d.setScene('wall');const count=id=>{d.draw({only:[id]});const a=d.pixels();d.draw({only:[]});const b=d.pixels();let changed=0;for(let i=0;i<a.length;i+=4)if(a[i]!==b[i]||a[i+1]!==b[i+1]||a[i+2]!==b[i+2])changed++;return changed;};const front=count('wall-front'),partial=count('wall-partial'),hidden=count('wall-camera-partial');return {pass:front>50&&partial>0&&partial<front&&hidden>0&&hidden<partial,frontPixels:front,partialPixels:partial,deeperPartialPixels:hidden};});
 await run('complete physical occlusion behind solid wall',()=>{const d=stageD;const opts={eye:{x:1040,y:420,z:50},camera:{x:1080,y:420,z:0}};d.draw({...opts,only:['wall-physical-hidden']});const a=d.digest(d.pixels());d.draw({...opts,only:[],overlays:['wall-physical-hidden']});const b=d.digest(d.pixels());return {pass:a.hash===b.hash,with:a,without:b};});
 await run('static seams and depth independent of draw submission order',()=>{const d=stageD;d.setScene('ramp');const hashes=[];for(let i=0;i<12;i++){d.draw({reverse:i%2===1});hashes.push(d.digest(d.pixels()).hash);}return {pass:new Set(hashes).size===1,hashes};});
 assert.deepEqual(errors,[]);const result={status:'PASS',runtime:process.version,browser:browser.version(),httpBytes:bytes,checks,errors,metadata:await page.evaluate(()=>stageD.metadata())};fs.writeFileSync(path.join(out,'browser-core.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks:checks.length,browser:browser.version()}));
 }finally{if(browser)await browser.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
