'use strict';
// Reproducible extraction of the shipped Pixi runtime and exact original avatar.
// No library upgrade, copied implementation edits, or production bootstrap changes.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),root=path.resolve(__dirname,'../..');
const src=fs.readFileSync(path.join(root,'assets/index-DKbV5Nv9.js'),'utf8');

const sourceSHA=crypto.createHash('sha256').update(src).digest('hex');
if(sourceSHA!=='af765f4f96d2ca2e4d6f681dc42c7ada5c8d0595b15a07b1473637e98d249552')throw Error('Locked production Pixi/game bundle changed; review extraction before rebuilding');
const engineEnd=src.indexOf('var WG=window.TFB_GEOMETRY'),artStart=src.indexOf('var $c=class extends O'),artEnd=src.indexOf(',el=[];function tl()',artStart);
if(engineEnd<0||artStart<engineEnd||artEnd<artStart)throw Error('Pinned runtime/actor extraction boundaries changed');
const browserSource=fs.readFileSync(path.join(root,'assets/browserAll-B-iwy0YI.js'),'utf8');
const bootstrapImport='import"./index-DKbV5Nv9.js";';
if(browserSource.split(bootstrapImport).length!==2)throw Error('Pinned browser extension import changed');
fs.writeFileSync(path.join(root,'assets/stageD-browser.js'),browserSource.replace(bootstrapImport,''));
const body=src.slice(0,engineEnd).replaceAll('browserAll-B-iwy0YI.js','stageD-browser.js')+'\n'+src.slice(artStart,artEnd)+';\nexport {ln as Application,I as Graphics,O as Container,w as Texture,$c as Avatar};\n';
fs.writeFileSync(path.join(root,'assets/stageD-pixi.js'),'// GENERATED by dev/stage_d/build_prototype.js; do not hand-edit.\n'+body);
const fixture=require('../fixtures/world_25d');fs.writeFileSync(path.join(root,'assets/stageD-world.json'),JSON.stringify(fixture)+'\n');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const provenance={source:'assets/index-DKbV5Nv9.js',sourceSHA256:hash(src),enginePrefixBytes:Buffer.byteLength(src.slice(0,engineEnd)),originalActorClassBytes:Buffer.byteLength(src.slice(artStart,artEnd)),runtime:'Pixi 8.21.0 (version from shipped runtime)',browserExtensionSourceSHA256:hash(browserSource),browserExtension:'Same shipped browser extension, with its sole game-bootstrap side-effect import removed; runtime dynamic import remapped to isolated copy.',method:'Exact engine prefix and exact avatar class, excluding game initialization. Original bundle remains byte-identical.',fixture:'dev/fixtures/world_25d.js',fixtureSHA256:hash(JSON.stringify(fixture))};
fs.writeFileSync(path.join(__dirname,'runtime-provenance.json'),JSON.stringify(provenance,null,2)+'\n');console.log(JSON.stringify(provenance));
