'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
process.env.ADMIN_PASSCODE=require('crypto').randomBytes(24).toString('hex');
const {fixture,server,launch,open,diagnostics}=require('./browser_support');
const out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});
async function difference(page,query){return page.evaluate(q=>{const s=__spatial,p=s.pass,o=s.state.renderOptions;p.render(o);const a=p.pixels();const next={...o};if(q.light)next.lights=o.lights.filter(l=>l.id!==q.light);else next.actors=o.actors.filter(p=>q.death?p.death!==q.death:p.id!==q.id);if(q.nv!==undefined){o.nv=q.nv;next.nv=q.nv;p.render(o);a.set(p.pixels());}p.render(next);const b=p.pixels();let changed=0;for(let i=0;i<a.length;i+=4)if(a[i]!==b[i]||a[i+1]!==b[i+1]||a[i+2]!==b[i+2])changed++;p.render(o);return{changed,error:p.gl.getError(),lights:o.lights,packets:o.actors.filter(p=>q.death?p.death===q.death:p.id===q.id)};},query);}
async function equip(c,kind){await c.page.evaluate(kind=>{__api.gear.eq.kind=kind;__api.H.equipment.kind=kind;},kind);await c.page.waitForFunction(k=>__sent.some(m=>m.t==='sp'&&m.samples.some(q=>q.presentation?.k===k)),kind);}
(async()=>{const s=await server(fixture());let browser,a,b;const checks=[];try{
 browser=await launch();a=await open(browser,s,'H3 lower');b=await open(browser,s,'H3 upper');await a.command({c:'freeze',on:1});
 await a.teleport({x:160,y:160,z:0,support:'support:ground-north'});await b.teleport({x:160,y:160,z:180,support:'support:upper-west'});
 const bid=await b.page.evaluate(()=>__api.H.id),aid=await a.page.evaluate(()=>__api.H.id);
 for(const kind of ['flashlight','headlamp','lantern']){await equip(b,kind);await a.page.waitForFunction(({id,kind})=>__spatial.state.lights.some(l=>l.id==='p'+id&&l.kind===kind),{id:bid,kind});const hidden=await difference(a.page,{light:'p'+bid});assert.equal(hidden.changed,0,kind+' upper emitter leaked');checks.push({name:kind+' actual peer emitter above slab',hidden});}
 await equip(a,'lantern');await a.page.waitForFunction(()=>__spatial.state.lights.some(l=>l.id==='p'+__api.H.id&&l.kind==='lantern'));const on=await difference(a.page,{light:'p'+aid});assert(on.changed>30);await a.page.keyboard.press('f');await a.page.waitForFunction(()=>!__spatial.state.lights.some(l=>l.id==='p'+__api.H.id));checks.push({name:'visible lantern positive control; OFF has no emitter or aura',on,off:await a.inspect()});await a.page.keyboard.press('f');
 await equip(a,'camcorder');await a.page.waitForFunction(()=>__cam.nv&&__spatial.state.lights.some(l=>l.id==='p'+__api.H.id&&l.channel==='ir'));
 const irOff=await difference(a.page,{light:'p'+aid,nv:false}),irOn=await difference(a.page,{light:'p'+aid,nv:true});assert.equal(irOff.changed,0);assert(irOn.changed>30);checks.push({name:'IR emitter invisible with sensor OFF, present with sensor ON',irOff,irOn});
 await b.page.evaluate(()=>{window.__deathKernelCalls=[];for(const k of ['begin','frame','advance','tick','fromEvent','restore']){const f=__dphys[k];__dphys[k]=function(...v){__deathKernelCalls.push(k);return f(...v);};}});
 await equip(b,'flashlight');await b.command({c:'preview',k:'hound',var:'A'});
 await a.page.waitForFunction(()=>__spatial.state.packets.some(p=>p.kind==='body'),null,{timeout:30000});
 const key=await a.page.evaluate(()=>__spatial.state.aftermath[0].key);const active=await a.page.evaluate(()=>({aftermath:__spatial.state.aftermath,packets:__spatial.state.packets}));checks.push({name:'canonical active aftermath in real production pass',active});
 const hiddenDeath=await difference(a.page,{death:key});assert.equal(hiddenDeath.changed,0,'upper aftermath through slab');assert(hiddenDeath.packets.some(p=>p.kind==='body')&&hiddenDeath.packets.filter(p=>p.kind.startsWith('hand:')).length===2&&hiddenDeath.packets.some(p=>p.kind==='light'));
 const hiddenBeam=await difference(a.page,{light:key+':beam'});assert.equal(hiddenBeam.changed,0);checks.push({name:'body/two hands/loose gear/decal/trail/replay and detached beam hidden',hiddenDeath,hiddenBeam});
 await b.page.waitForFunction(()=>__api.death().finished&&!document.getElementById('caught').hidden,null,{timeout:30000});
 const lifecycle=await b.page.evaluate(()=>({kernelCalls:__deathKernelCalls,corpseId:__api.death().corpseId,clientBodies:__api.bodyCount(),sent:__commands.filter(m=>m.t==='b'||m.t==='fx'&&m.k==='death'),aftermath:__spatial.state.aftermath}));assert.deepEqual(lifecycle.kernelCalls,[]);assert.equal(lifecycle.clientBodies,0);assert.deepEqual(lifecycle.sent,[]);assert.equal(lifecycle.corpseId,key);checks.push({name:'real caught UI completes from server time; no client death kernel or outcome',lifecycle});
 await a.teleport({x:220,y:160,z:180,support:'support:upper-west'});await a.page.waitForTimeout(500);const visibleDeath=await difference(a.page,{death:key});assert(visibleDeath.changed>30);checks.push({name:'same canonical aftermath has visible positive control on physical floor',visibleDeath});
 await a.page.screenshot({path:path.join(out,'aftermath-observer.png')});await b.page.screenshot({path:path.join(out,'victim-caught.png')});a.validate();b.validate();
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',browser:browser.version(),gpu:(await a.inspect()).gpu,checks,resources:[a.http,b.http],errors:[a.errors,b.errors]},null,2));console.log('PASS H-Z14 production visible/IR and Stage G aftermath masks/lifecycle');
 }catch(e){for(const [id,c]of [['a',a],['b',b]])if(c){await c.page.screenshot({path:path.join(out,id+'-failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,id+'-diagnostic.json'),JSON.stringify(await diagnostics(c),null,2));}fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),stack:e.stack,checks,server:s.log},null,2));throw e;}finally{if(browser)await browser.close();await s.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
