'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
process.env.ADMIN_PASSCODE=require('crypto').randomBytes(24).toString('hex');
const {fixture,server,launch,open,pixels,diagnostics}=require('./browser_support');
const out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});
(async()=>{const s=await server(fixture());let browser,a,b;const checks=[];try{
 browser=await launch();a=await open(browser,s,'H1 lower');
 const first=await pixels(a.page);assert(first.lit>1000&&first.error===0,'actual completed production pixels');
 checks.push({name:'production Pixi boot and composed pixels',pixels:first,state:await a.inspect()});
 await a.page.screenshot({path:path.join(out,'lower.png')});
 await a.teleport({x:700,y:148,z:32.5,support:'support:ramp'});
 await a.page.evaluate(()=>__spatial.state.trace=[]);await a.page.keyboard.down('d');await a.page.waitForTimeout(1800);await a.page.keyboard.up('d');await a.page.waitForTimeout(500);
 const ramp=await a.page.evaluate(()=>({trace:__spatial.state.trace,pose:{x:__api.H.x,z:__api.H.z},state:__spatial.inspect()}));
 assert(ramp.pose.x>750&&ramp.pose.z>50);assert(ramp.trace.length>2&&ramp.trace.every(p=>[p.x,p.y,p.z].every(Number.isFinite)));
 checks.push({name:'real fixed-tick keyboard ramp',...ramp});await a.page.screenshot({path:path.join(out,'ramp.png')});
 b=await open(browser,s,'H1 peer');
 await b.teleport({x:880,y:660,z:120,support:'support:balcony'});
 await a.teleport({x:950,y:660,z:120,support:'support:balcony'});
 const bid=await b.page.evaluate(()=>__api.H.id);
 await a.page.waitForFunction(id=>__spatial.state.packets.some(p=>p.id==='p'+id&&p.z>119),bid);
 await a.page.evaluate(()=>window.__peerTrace=[]);await a.page.evaluate(id=>{window.__peerCapture=setInterval(()=>{const p=__spatial.state.packets.find(p=>p.id==='p'+id);if(p)__peerTrace.push({...p});},40);},bid);
 await b.page.keyboard.down('s');await b.page.waitForTimeout(1600);await b.page.keyboard.up('s');await b.page.waitForTimeout(1000);
 const falling=await a.page.evaluate(()=>{clearInterval(__peerCapture);return __peerTrace;});fs.writeFileSync(path.join(out,'peer-fall-raw.json'),JSON.stringify(falling,null,2));
 assert(falling.some(p=>p.z>100)&&falling.some(p=>p.z<0),'replicated balcony fall changes true Z');assert(falling.some(p=>p.mode==='airborne'),'peer samples include physical falling state');
 checks.push({name:'real second production client falling interpolation',trace:falling,state:await b.inspect()});await a.page.screenshot({path:path.join(out,'peer-fall.png')});
 await a.command({c:'freeze',on:1});
 await a.teleport({x:160,y:160,z:180,support:'support:upper-west'});
 await a.command({c:'spatial-entity',kind:'hound',pose:{x:200,y:160,z:180,support:'support:upper-west'}});
 await a.command({c:'spatial-entity',kind:'smiler',pose:{x:240,y:160,z:180,support:'support:upper-west'}});
 await a.page.waitForFunction(()=>['hound','smiler'].every(k=>__spatial.state.packets.some(p=>p.kind===k&&p.z>=180)));
 const actors=await a.inspect();checks.push({name:'server Hound and Smiler full XYZ procedural actors',state:actors});await a.page.screenshot({path:path.join(out,'entities.png')});
 a.validate();b.validate();const result={status:'PASS',browser:browser.version(),gpu:actors.gpu,checks,errors:[a.errors,b.errors],console:[a.consoleErrors,b.consoleErrors],resources:[a.http,b.http],externalFailures:[a.failed,b.failed]};
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2)+'\n');console.log('PASS H1 production pixels, local ramp, replicated peer fall, Hound and Smiler XYZ');
 }catch(e){for(const [id,c]of [['a',a],['b',b]])if(c){await c.page.screenshot({path:path.join(out,id+'-failure.png')}).catch(()=>{});fs.writeFileSync(path.join(out,id+'-diagnostic.json'),JSON.stringify(await diagnostics(c),null,2));}fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),stack:e.stack,checks,server:s.log},null,2));throw e;}finally{if(browser)await browser.close();await s.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
