'use strict';
const assert=require('assert'),{G,M,fixture,clone,world,box,mover}=require('./helpers');
let passed=0;const results=[];function test(name,fn){try{fn();passed++;results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){console.error('FAIL '+name);throw e;}}
const near=(a,b,e=.051)=>assert(Math.abs(a-b)<=e,`${a} != ${b}`),shape=M.PROFILES.stand;
const flat=()=>world([box('ground',0,0,1200,1000,-16,0)]);
const compile=d=>{const g=G.compile(d);return {g,m:M.create(g)};};
const walk=(m,b,n,vx=0,vy=0)=>{for(let i=0;i<n;i++){b.vx=vx;b.vy=vy;m.step(b);assert([b.x,b.y,b.z,b.vx,b.vy,b.vz].every(Number.isFinite));assert(m.geometry.clearance(b.shape,b).fits,'solid occupancy');}return b;};
test('schema / numeric bounds / convexity / references / duplicate geometry',()=>{
 assert(G.validate(fixture));for(const mutate of [d=>d.bounds.max.z=NaN,d=>d.bounds.min.z=400,d=>d.solids[0].upper.c=Infinity,d=>d.solids[0].footprint.reverse(),d=>d.supportPatches[0].plane.c++,d=>d.solids[0].materialId='bad',d=>d.solids[0].upper.c=-200,d=>d.anchors[0].position.z=900]){const d=clone(fixture);mutate(d);assert.throws(()=>G.compile(d));}
 const a=box('a',0,0,100,100,0,10),b=box('b',0,0,100,100,0,10);assert.throws(()=>G.compile(world([a,b])),/duplicate solid/);
 b.footprint[1].x=120;b.footprint[2].x=120;b.channels.ir=false;assert.throws(()=>G.compile(world([a,b])),/conflicting/);
 assert.throws(()=>G.compile(world([a],{contentHash:'corrupt'})),/hash/);
});
test('deterministic identity and required stable ID ordering',()=>{const d=clone(fixture);near(G.compile(d).identity.contentHash.length,64);assert.equal(G.compile(d).identity.contentHash,G.compile(clone(d)).identity.contentHash);d.solids.reverse();assert.throws(()=>G.compile(d),/canonical ID order/);});
test('stacked contextual support, negative elevation, clearance, no maximum-Z shortcut',()=>{
 const g=G.compile(fixture);for(const z of [0,180]){const s=g.supports(shape,{x:160,y:160,z},[z-.1,z+.1]);assert.equal(s.length,1);near(s[0].z,z);}
 assert(!g.clearance(shape,{x:160,y:160,z:150}).fits);assert(g.clearance(shape,{x:160,y:160,z:180}).fits);assert.throws(()=>g.supports(shape,{x:0,y:0,z:0},[-Infinity,Infinity]));
 assert.equal(g.supports(shape,{x:160,y:160,z:0},[-.1,.1],null,{x:0,y:0,z:1}).length,0);
});
test('exact finite footprint slope extrema and circular corner',()=>{const g=G.compile(fixture),p=g.supportPatch('support:ramp');near(g.footprintRange(p.polygon,{x:995,y:148},15,p.plane).max,180);near(g.footprintRange(p.polygon,{x:1000,y:148},15,p.plane).max,180);assert.equal(g.footprintRange(p.polygon,{x:630,y:80},15,p.plane),null);});
test('stationary stability, seam continuity and previous-support tie',()=>{const d=world([box('a',0,0,200,400,-10,0),box('b',200,0,200,400,-10,0)]),{g,m}=compile(d),b=m.initialize({x:100,y:100,z:0});walk(m,b,300);near(b.z,0);walk(m,b,120,100);near(b.x,300);near(b.z,0);assert.equal(b.supportId,'support:b');assert.equal(b.diagnostics.length,0);const s=g.supports(shape,{x:200,y:100,z:0},[0,0],'support:b');assert.equal(s[0].id,'support:b');});
test('ramp ascent, landing seam, reverse descent, physical path speed',()=>{
 const {m}=compile(fixture),b=m.initialize({x:600,y:148,z:0});let prev={...b};for(let i=0;i<300;i++){walk(m,b,1,100);assert(Math.hypot(b.x-prev.x,b.y-prev.y,b.z-prev.z)<=100/60+.001);prev={...b};}assert(b.x>1030);near(b.z,180);walk(m,b,300,-100);assert(b.x<620);near(b.z,0);assert.equal(b.diagnostics.length,0);
});
test('ramp diagonal/reversal and side departure',()=>{const {m}=compile(fixture),b=m.initialize({x:760,y:145,z:62.5});walk(m,b,10,70,20);assert(b.z>62.5);walk(m,b,10,-70,-20);near(b.z,62.5,.06);walk(m,b,100,0,100);assert.equal(b.supportId,'support:ground-north');near(b.z,0);assert.equal(b.diagnostics.length,0);});
test('ramp overhead blocks full body',()=>{const d=world([box('floor',0,0,800,300,-10,0),box('ramp',200,80,300,120,{a:.5,b:0,c:-110},{a:.5,b:0,c:-100}),box('roof',350,50,200,200,110,125,true)]),{m}=compile(d),b=m.initialize({x:150,y:140,z:0});walk(m,b,240,100);assert(b.x<335.1,'head must stop before roof');});
test('real 15 tread stairs: finite lift, repeated progression, reverse/down',()=>{const {m}=compile(fixture),b=m.initialize({x:368,y:90,z:0});let prev=0,saw=false;for(let i=0;i<410;i++){walk(m,b,1,0,100);assert(b.z-prev<=M.POLICY.stepLiftMax/60+.001);saw ||=!!b.step;prev=b.z;}assert(saw);assert(b.y>600&&b.y<640);near(b.z,180,.06);walk(m,b,300,0,-100);assert(b.z<120);assert.equal(b.diagnostics.length,0);});
test('excessive riser and overhead step rejected',()=>{for(const ceiling of [false,true]){const solids=[box('floor',0,0,600,400,-10,0),box('step',250,0,100,400,0,ceiling?12:24)];if(ceiling)solids.push(box('roof',200,0,200,400,65,80,true));const {m}=compile(world(solids)),b=m.initialize({x:200,y:150,z:0});walk(m,b,120,100);assert(b.x<235.1);near(b.z,0);}});
test('step interruption and sideways departure do not write endpoint',()=>{for(const direction of [-1,0]){const {m}=compile(fixture),b=m.initialize({x:368,y:100,z:0});let n=0;while(!b.step&&n++<30)walk(m,b,1,0,100);assert(b.step);walk(m,b,2,0,100);const before={...b};walk(m,b,1,direction===0?100:0,direction===-1?-100:0);assert.equal(b.step,null);assert(Math.hypot(b.x-before.x,b.y-before.y)<2);assert(b.z-before.z<.1);}});
test('fall from balcony, lower landing exactly once, carried momentum',()=>{const {m}=compile(fixture),b=m.initialize({x:880,y:660,z:120});let lands=0,air=false;for(let i=0;i<120;i++){walk(m,b,1,0,100);lands+=b.events.filter(e=>e.type==='land').length;air ||=b.motionMode==='airborne';}assert(air);assert.equal(lands,1);assert.equal(b.supportId,'support:lower-platform');near(b.z,-96);assert(b.y>850);});
test('fast fall hits first thin slab, never upper floor behind trajectory',()=>{const d=world([box('bottom',0,0,500,500,-110,-100),box('thin',0,0,500,500,39.9,40),box('upper',0,0,500,500,240,250)]),{m,g}=compile(d),b=m.initialize({x:100,y:100,z:180,vz:-30000});m.step(b);assert.equal(b.supportId,'support:thin');near(b.z,40,.06);assert(b.events.some(e=>e.type==='land'&&e.impactSpeed>30000));assert(g.clearance(b.shape,b).fits);});
test('upward impulse hits underside; horizontal fast sweep catches finite wall/corner',()=>{const {m,g}=compile(fixture),b=m.initialize({x:160,y:160,z:70,vz:15000});m.step(b);assert(b.z<109);assert(b.vz<=0);assert.notEqual(b.supportId,'support:upper-west');const h=g.sweep(shape,{x:900,y:400,z:0},{x:400,y:0,z:0});assert.equal(h.primitiveId,'solid:solid-wall');assert(h.t<.5);assert(!g.sweep(shape,{x:1080,y:330,z:0},{x:4,y:0,z:0}));});
test('clearance crawl-under and rejected stand preserves root',()=>{const {g,m}=compile(fixture),b=m.initialize({x:140,y:770,z:0},'crawl');assert(!m.posture(b,'stand'));near(b.z,0);assert.equal(b.shape.height,24);assert(!g.clearance(M.PROFILES.crouch,b).fits);walk(m,b,90,100);assert(b.x>280);assert(m.posture(b,'stand'));});
test('physical rays include vertical/oblique slab, opening and window',()=>{const g=G.compile(fixture);assert(g.raycast({x:160,y:160,z:100},{x:160,y:160,z:200}));assert(!g.raycast({x:368,y:90,z:100},{x:368,y:90,z:200}));assert(!g.raycast({x:680,y:380,z:70},{x:740,y:380,z:70}));assert(g.raycast({x:680,y:380,z:20},{x:740,y:380,z:20}));assert.throws(()=>g.contact({},{}),/NOT IMPLEMENTED/);assert.throws(()=>g.traceSupportMotion({},[],1),/NOT IMPLEMENTED/);});
test('Z translation metamorphic sweep and support identity',()=>{const a=flat(),b=clone(a);for(const s of b.solids){s.lower.c+=53;s.upper.c+=53;}for(const p of b.supportPatches)p.plane.c+=53;const ga=G.compile(a),gb=G.compile(b),ha=ga.sweep(shape,{x:100,y:100,z:150},{x:0,y:0,z:-300}),hb=gb.sweep(shape,{x:100,y:100,z:203},{x:0,y:0,z:-300});near(ha.t,hb.t);assert.equal(ha.primitiveId,hb.primitiveId);});
test('world lower bound event once; no z=0 recovery snap',()=>{const {m}=compile(world([])),b=m.initialize({x:100,y:100,z:-490});let events=0;for(let i=0;i<60;i++){m.step(b);events+=b.events.filter(e=>e.type==='world-lower-bound').length;}assert(b.z< -900);assert.equal(events,1);assert.throws(()=>m.step(b,.1),/fixed/);});
test('real move.js acceleration, sprint, radius, exhausted recovery 36, deep carpet',()=>{const a=mover(flat(),{x:100,y:500,z:0});a.step(1,0,true);assert(a.H.vx>0&&a.H.vx<100);assert.equal(a.H.shape.radius,15);assert(a.H.stamina<100);a.H.stamina=35.8;a.H.exhausted=true;a.step();assert(a.H.exhausted);for(let i=0;i<4;i++)a.step();assert(!a.H.exhausted);const d=flat();d.materials[0].noiseClass='deep';const deep=mover(d,{x:100,y:500,z:0}),normal=mover(flat(),{x:100,y:500,z:0});for(let i=0;i<100;i++){deep.step(1,0,true);normal.step(1,0,true);}assert(deep.H.x<normal.H.x);assert(deep.H.stamina<normal.H.stamina);});
test('real move.js crouch/crawl and blocked stand, slide cost and volume',()=>{const a=mover(fixture,{x:140,y:770,z:0});a.mv.crouch=true;a.mv.s='crawl';a.step(1);assert.equal(a.mv.s,'crawl');assert.equal(a.H.shape.height,24);a.step(1,0,false,true);assert.equal(a.mv.s,'crawl');const b=mover(flat(),{x:100,y:500,z:0});for(let i=0;i<50;i++)b.step(1,0,true);const stamina=b.H.stamina;b.step(1,0,true,true);assert.equal(b.mv.s,'slide');assert.equal(b.H.shape.height,25);assert(b.H.stamina<stamina);});
test('real move.js finite collision-checked vault and cost, overhead rejects',()=>{
 const prop={id:'test-low',cx:260,cy:200,cross:'x',topZ:20,rect:{x:250,y:100,w:20,h:200}};
 for(const blocked of [false,true]){const ss=[box('floor',0,0,1200,1000,-16,0),box('low',250,100,20,200,0,20)];if(blocked)ss.push(box('roof',220,100,100,200,70,85,true));const a=mover(world(ss),{x:170,y:200,z:0},[prop]);let saw=false,maxZ=0;for(let i=0;i<100;i++){a.step(1,0,true);saw ||=a.mv.s==='vault';maxZ=Math.max(maxZ,a.H.z);assert(a.geometry.clearance(a.H.shape,a.H).fits);}if(blocked){assert(!saw);assert(a.H.x<236);}else{assert(saw);assert(maxZ>=20);assert(a.H.x>300);assert(a.H.stamina<100);}}
});
console.log(JSON.stringify({status:'PASS',groups:passed,results},null,2));
