'use strict';
const assert=require('node:assert/strict'),{field}=require('./fixture'),{special}=require('../stage_e/test_motion'),{mover}=require('../stage_c/helpers'),{server,connect,wait,sleep}=require('./wire');
async function run(mode){let d=mode==='vault'||mode==='crawl'?special(mode):field();if(mode==='vault'){d.traversalLinks[0].profileIds.push('profile:player-stand');d.traversalLinks[0].obstacleId='solid:low';}
 if(mode==='vault'||mode==='crawl')d.anchors=[{id:'anchor:spawn',kind:'spawn',position:{x:170,y:200,z:0},yaw:0,supportId:'support:floor',spaceId:null,colliderProfileId:'profile:player-stand'}];
 const props=mode==='vault'?[{id:'solid:low',cx:260,cy:200,cross:'x',topZ:20,rect:{x:250,y:0,w:20,h:400}}]:[],s=await server(d);let c;
 try{c=await connect(s,d);await c.join();await c.admin();const r=mover(d,c.client.anchor,props),start=c.client.anchor.tick;let tick=start,saw=false,transition=false,lastCorrection=c.corrections.length;for(let i=0;i<180;i++){r.step(1,0,mode==='slide'||mode==='vault',mode==='crawl'||mode==='slide'&&i===60);saw ||= r.mv.s===mode;const h=r.H,q={tick:++tick,x:h.x,y:h.y,z:h.z,vx:h.vx,vy:h.vy,yaw:0,posture:r.mv.s,support:h.supportId,mv:{s:mode==='crawl'?4:mode==='slide'?6:1,st:h.stamina,sp:r.mv.speed}};if(r.mv.vault)q.vault={link:'link:vault',quality:r.mv.vault.q};await wait(()=>c.last.protocol.simTick>=tick,'credit');c.send(c.client.proposal([q]));await sleep(17);if(c.corrections.length>lastCorrection){transition=c.corrections.at(-1).cause==='physical-transition';if(transition)break;throw Error(mode+' unexpected correction '+c.corrections.at(-1).cause+' at input '+i);}}
 assert(saw,mode+' real motor state');if(mode==='vault'){assert(transition);await wait(()=>c.corrections.at(-1).cause==='grounded','vault completion');assert(c.client.pose.x>270);assert(c.client.pose.z<.11);}else assert(c.last.spatialStats.accepted>120);console.log(JSON.stringify({status:'PASS',mode,saw,transition,pose:c.client.pose,stats:c.last.spatialStats}));
 }finally{c?.close();await s.close();}}
(async()=>{for(const mode of ['slide','crawl','vault'])await run(mode);})().catch(e=>{console.error(e);process.exitCode=1;});
