'use strict';
const assert=require('node:assert/strict'),P=require('../../spatial_protocol'),{History}=require('../../spatial_history'),M=require('../../world_motion'),G=require('../../world_geometry'),{fixture}=require('../stage_e/fixture'),{field}=require('./fixture');
const d=fixture(),g=G.compile(d),m=M.create(g),manifest=P.manifest(g,'world-one',0);
function wire(body,tick,id='h1',generation=1,disc=0){return JSON.parse(JSON.stringify(P.pose(body,{worldEpoch:'world-one',entityId:id,generation,tick,seq:tick,discontinuity:disc},g)));}
function trajectory(name,start,v,n){const b=m.initialize({...start}),poses=[];for(let i=0;i<n;i++){b.vx=v.x;b.vy=v.y;m.step(b);if(i%3===0||b.events.length)poses.push(wire(b,i+1));}let held=0,drawn=0;const H=new History(g);H.world(manifest);for(const p of poses)H.ingest([p],p.tick/60*1000); // separate interval checks keep the actual eight-sample cap
 for(let i=1;i<poses.length;i++){const h=new History(g);h.world(manifest);h.ingest([poses[i-1],poses[i]],poses[i].tick/60*1000);for(let j=0;j<10;j++){const p=h.at('h1',poses[i-1].tick+(poses[i].tick-poses[i-1].tick)*j/10);assert(g.clearance(M.PROFILES.stand,p).fits,name+' rendered through solid');drawn++;held+=Math.hypot(p.x-poses[i-1].x,p.y-poses[i-1].y,p.z-poses[i-1].z)<1e-8;}}
 const schedules=[15,30,60,120,144,240,360],signature=[];for(const fps of schedules){const h=new History(g);h.world(manifest);let idx=0;for(let frame=0;frame<=fps*Math.ceil(n/60);frame++){const tick=frame/fps*60;while(idx<poses.length&&poses[idx].tick<=tick+6){h.ingest([poses[idx]],poses[idx].tick/60*1000);idx++;}h.at('h1',tick);}const before=JSON.stringify(h.hist),q=h.at('h1',poses.at(-1).tick-1);assert.equal(JSON.stringify(h.hist),before);signature.push(q);}assert(signature.every(q=>JSON.stringify(q)===JSON.stringify(signature[0])));return {name,poses:poses.length,drawn,held,schedules};}
const results=[trajectory('stairs',{x:368,y:90,z:0},{x:0,y:118},360),trajectory('drop/landing',{x:880,y:690,z:120},{x:0,y:172},70),trajectory('ramp',{x:620,y:148,z:0},{x:172,y:0},180)];
const h=new History(g);h.world(manifest);const a=wire(m.initialize({x:160,y:160,z:0}),1),b=wire(m.initialize({x:160,y:160,z:180}),4);h.ingest([a,b],80);assert.equal(h.at('h1',2).z,0);const tp={...b,tick:5,seq:5,discontinuity:1};h.ingest([tp],100);assert.equal(h.at('h1',1).z,180);h.ingest([a],110);assert.equal(h.at('h1',1).z,180);
const edge=wire(m.initialize({x:880,y:695,z:120,vx:0,vy:172}),9);h.ingest([{...edge,discontinuity:2}],150);assert.equal(h.at('h1',100).y,695);
let resets=0;const f=G.compile(field()),r=new History(f,()=>resets++),fm=P.manifest(f,'old',3600),old={...P.pose(M.create(f).initialize({x:5000,y:500,z:0}),{worldEpoch:'old',entityId:'h1',generation:1,tick:3600,seq:3600},f)};r.world(fm);r.ingest([old],0);const oldOff=r.offset;r.world({...fm,worldEpoch:'new',simTick:60});const fresh={...old,worldEpoch:'new',x:1000,z:200,support:'support:upper',navSurface:'nav:upper',tick:60,seq:60};r.ingest([fresh],1000);assert.equal(r.sample('h1',1000).x,1000);assert.equal(r.sample('h1',1000).z,200);assert.notEqual(r.offset,oldOff);r.ingest([old],1100);assert.equal(r.sample('h1',1100).x,1000);const count=resets;for(let i=0;i<200;i++)r.ingest([{...fresh,tick:61+i,seq:61+i}],1000+i*17+(i%4)*30);assert.equal(resets,count);assert(r.hist.get('h1').length<=8);
console.log(JSON.stringify({status:'PASS',Z23:results,teleport:true,missingTransitionHold:true,unknownLedgeHold:true,Z22:{old:{x:5000,time:60,z:0},new:{x:1000,time:1,z:200},explicitReset:true,jitterResets:0}},null,2));
