'use strict';
const cp=require('node:child_process'),net=require('node:net'),path=require('node:path'),fs=require('node:fs'),os=require('node:os'),P=require('../../spatial_protocol'),G=require('../../world_geometry');
const sleep=t=>new Promise(r=>setTimeout(r,t));
async function wait(fn,label,ms=5000){const end=Date.now()+ms;while(Date.now()<end){const r=fn();if(r)return r;await sleep(10);}throw Error('Timeout '+label);}
async function server(def){const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'tfb-f-'));const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));if(def)fs.writeFileSync(path.join(tmp,'world.json'),JSON.stringify(def));const child=cp.spawn(process.execPath,['server.js',String(port)],{cwd:path.resolve(__dirname,'../..'),env:{...process.env,...(def?{TFB_WORLD:path.join(tmp,'world.json')}:{})},stdio:['ignore','pipe','pipe']});let log='';child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);await wait(()=>log.includes('ONLINE')||child.exitCode!==null,'server startup');if(child.exitCode!==null)throw Error(log);return {port,child,tmp,get log(){return log},async close(){child.kill();await wait(()=>child.exitCode!==null||child.signalCode,'server shutdown');fs.rmSync(tmp,{recursive:true,force:true});}};}
async function connect(s,def,room='f'){const g=G.compile(def),history=new (require('../../spatial_history').History)(g),client=new P.Client(P.manifest(g,'local',0)),ws=new WebSocket('ws://127.0.0.1:'+s.port+'/ws?room='+room),messages=[];let hi,last,corrections=[];
 const send=m=>ws.send(JSON.stringify(['hello','admin','ping','sp'].includes(m.t)?m:client.action(m)));ws.onmessage=e=>{const m=JSON.parse(e.data);messages.push(m);if(messages.length>4000)messages.shift();if(m.t==='hi'){hi=m;send(client.hello(m.protocol));history.world(m.protocol);}if(m.t==='world'){send(client.hello(m.protocol));history.world(m.protocol);}if(m.t==='correction'){if(client.accept(m.pose))corrections.push(m);}if(m.t==='s'){last=m;history.ingest(m.spatial||[],Date.now());if(m.pose)client.accept(m.pose);}};
 await wait(()=>hi&&client.pose,'handshake');return {ws,client,history,messages,corrections,send,get last(){return last},get hi(){return hi},async join(){const life=client.life;send({t:'join'});await wait(()=>client.life>life,'join');},async admin(){send({t:'admin',pass:process.env.ADMIN_PASSCODE||'smoor',quiet:1});await wait(()=>messages.some(m=>m.t==='admin'&&m.ok),'admin');},async teleport(pose){const n=corrections.length;send({t:'a',c:'spatial-tp',pose});await wait(()=>corrections.length>n,'teleport');},close(){ws.close();}};}
module.exports={server,connect,wait,sleep};
