'use strict';
// DATA validation, not geometry compilation, collision, navigation or physics.
const collections=['solids','supportPatches','navSurfaces','traversalLinks','spaces','portals','materials','lights','viewGroups','anchors','colliderProfiles'];
const required={solids:['footprint','lower','upper','materialId','channels'],supportPatches:['polygon','plane','normal','solidId','materialId','navSurfaceId','supports'],navSurfaces:['patchIds','origin','cellSize','boundaryLinkIds','chart','clearanceProfileIds'],traversalLinks:['kind','fromSurfaceId','toSurfaceId','entry','exit','corridor','supportPatchIds','profileIds','capabilityFlags','durationRule','progressRule','interruptionRule','landingRule','costRule','directed','clearanceRequired'],spaces:['bounds','portalIds','volumeSpec'],portals:['fromSpaceId','toSpaceId','polygon','channels','traversalLinkId'],materials:['friction','noiseClass','visibleTransmission','irTransmission','acousticTransmission'],lights:['position','direction','channel','range','power','supportId','spaceId'],viewGroups:['solidIds','spaceIds','cutawayEligible'],anchors:['kind','position','yaw','supportId','spaceId','colliderProfileId'],colliderProfiles:['radius','height','eyeHeight','maxSlopeDegrees','maxStepRise','stepLiftMax','capabilities']};
function validate(w){const errors=[],refs={};const err=s=>errors.push(s);const walk=(v,p)=>{if(typeof v==='number'&&!Number.isFinite(v))err(p+' nonfinite');if(v&&typeof v==='object')for(const [k,q] of Object.entries(v))walk(q,p+'.'+k);};walk(w,'world');
 for(const k of ['schemaVersion','assetId','geometryRevision','geometryMode','units','bounds'])if(w[k]===undefined)err('Missing '+k);
 if(w.schemaVersion!==1)err('Unknown schemaVersion');if(!['flat-compat','spatial'].includes(w.geometryMode))err('Invalid geometryMode');if(w.units!=='legacy-world-unit')err('Invalid units');
 const point=(p,d,where)=>{if(!p||d.some(k=>typeof p[k]!=='number'||!Number.isFinite(p[k])))err(where+' invalid point');};
 const bounds=(b,where)=>{point(b?.min,['x','y','z'],where+'.min');point(b?.max,['x','y','z'],where+'.max');if(b?.min&&b?.max)for(const k of ['x','y','z'])if(!(b.min[k]<b.max[k]))err(where+' inverted bounds');};bounds(w.bounds,'world.bounds');
 const all=new Set();
 for(const c of collections){const a=w[c];refs[c]=new Set();if(!Array.isArray(a)){err('Missing collection '+c);continue;}let prev='';for(const o of a){if(!o||typeof o.id!=='string'||!o.id.includes(':')){err(c+' invalid explicit ID');continue;}if(all.has(o.id))err('Duplicate ID '+o.id);all.add(o.id);refs[c].add(o.id);if(prev&&prev>=o.id)err(c+' not canonical ID order');prev=o.id;for(const k of required[c])if(o[k]===undefined)err(o.id+' missing '+k);}}
 const ref=(type,id,where,nullable=false)=>{if(nullable&&id===null)return;if(!refs[type].has(id))err(where+' invalid '+type+' reference '+id);};
 const list=(type,ids,where)=>{if(!Array.isArray(ids)){err(where+' not an array');return;}if(new Set(ids).size!==ids.length)err(where+' duplicate reference');for(const id of ids)ref(type,id,where);};
 const poly=(p,dim,where)=>{if(!Array.isArray(p)||p.length<3){err(where+' invalid polygon');return;}for(const q of p)point(q,dim,where);};
 for(const o of w.solids||[]){poly(o.footprint,['x','y'],o.id);for(const p of [o.lower,o.upper])point(p,['a','b','c'],o.id);ref('materials',o.materialId,o.id);if(o.lower&&o.upper)for(const v of o.footprint||[])if(o.lower.a*v.x+o.lower.b*v.y+o.lower.c>=o.upper.a*v.x+o.upper.b*v.y+o.upper.c)err(o.id+' inverted/zero thickness');}
 for(const o of w.supportPatches||[]){poly(o.polygon,['x','y'],o.id);point(o.plane,['a','b','c'],o.id);point(o.normal,['x','y','z'],o.id);ref('solids',o.solidId,o.id);ref('materials',o.materialId,o.id);ref('navSurfaces',o.navSurfaceId,o.id,true);}
 for(const o of w.navSurfaces||[]){list('supportPatches',o.patchIds,o.id);list('traversalLinks',o.boundaryLinkIds,o.id);list('colliderProfiles',o.clearanceProfileIds,o.id);point(o.origin,['x','y'],o.id);if(!(o.cellSize>0))err(o.id+' invalid cellSize');}
 for(const o of w.traversalLinks||[]){if(!['walk-seam','ramp','stairs','step','drop','crawl','vault'].includes(o.kind))err(o.id+' invalid link kind');for(const k of ['fromSurfaceId','toSurfaceId'])ref('navSurfaces',o[k],o.id);list('supportPatches',o.supportPatchIds,o.id);list('colliderProfiles',o.profileIds,o.id);for(const k of ['entry','exit','corridor']){if(!Array.isArray(o[k])||!o[k].length)err(o.id+' empty '+k);else for(const p of o[k])point(p,['x','y','z'],o.id);}if(o.directed!==true)err(o.id+' link must be explicitly directed');}
 for(const o of w.spaces||[]){bounds(o.bounds,o.id);list('portals',o.portalIds,o.id);}
 for(const o of w.portals||[]){for(const k of ['fromSpaceId','toSpaceId'])ref('spaces',o[k],o.id);poly(o.polygon,['x','y','z'],o.id);ref('traversalLinks',o.traversalLinkId,o.id,true);}
 for(const o of w.lights||[]){point(o.position,['x','y','z'],o.id);point(o.direction,['x','y','z'],o.id);if(!['visible','ir'].includes(o.channel))err(o.id+' invalid light channel');ref('supportPatches',o.supportId,o.id,true);ref('spaces',o.spaceId,o.id,true);}
 for(const o of w.viewGroups||[]){list('solids',o.solidIds,o.id);list('spaces',o.spaceIds,o.id);}
 for(const o of w.anchors||[]){point(o.position,['x','y','z'],o.id);ref('supportPatches',o.supportId,o.id);ref('spaces',o.spaceId,o.id,true);ref('colliderProfiles',o.colliderProfileId,o.id);}
 for(const o of w.colliderProfiles||[])if(!(o.radius>0&&o.height>0&&o.eyeHeight>=0&&o.eyeHeight<=o.height))err(o.id+' invalid profile dimensions');
 return {status:errors.length?'SCHEMA INVALID':'SCHEMA VALID',physics:'NOT IMPLEMENTED BY DESIGN',errors};}
module.exports={collections,required,validate};
