'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),{server}=require('../stage_f/wire'),{field}=require('../stage_f/fixture'),{launch,get}=require('../stage_d/browser_support');
(async()=>{const out=path.resolve(process.argv[2]||'dev/stage_g/evidence/g5/browser');fs.mkdirSync(out,{recursive:true});const d=field(),s=await server(d);let browser;const errors=[],failed=[],http=[];try{
 browser=await launch();const page=await browser.newPage({viewport:{width:960,height:720}});page.on('pageerror',e=>errors.push(String(e)));page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()?.errorText}));
 for(const file of ['world_motion.js','dphys.js','spatial_protocol.js','spatial_history.js','mp.js']){const r=await get(s.port,'/'+file);assert.equal(r.status,200,file);assert(r.bytes.equals(fs.readFileSync(path.join(__dirname,'../..',file))));http.push({file,status:r.status,bytes:r.bytes.length});}
 for(const file of ['ai.js','sim.js','death_srv.js','server.js'])assert.equal((await get(s.port,'/'+file)).status,404,file+' remains server-only');
 await page.goto('http://127.0.0.1:'+s.port+'/stage_d.html?manual=1');await page.waitForFunction(()=>window.stageD?.ready);
 for(const file of ['world_motion.js','dphys.js','spatial_protocol.js','spatial_history.js'])await page.addScriptTag({url:'/'+file});
 await page.evaluate(({d,pass})=>{
  const g=TFB_GEOMETRY.compile(d),client=new TFB_PROTOCOL.Client(TFB_PROTOCOL.manifest(g,'local',0)),history=new TFB_HISTORY.History(g),ws=new WebSocket('ws://'+location.host+'/ws?room=g5-browser');
  window.g5={g,client,history,ws,records:[],comparisons:0,maxError:0,discreteErrors:[],send:m=>ws.send(JSON.stringify(['hello','admin'].includes(m.t)?m:client.action(m)))};
  ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.t==='hi'||m.t==='world'){g5.send(client.hello(m.protocol));history.world(m.protocol);}if(m.t==='correction')client.accept(m.pose);if(m.t==='s'&&m.pose)client.accept(m.pose);if(m.t==='admin')g5.admin=m.ok;
   if(m.t==='bodies'&&client.bodies(m)){for(const r of client.aftermaths.values()){
    const a=r.spatial,old=g5.previous;if(old&&old.key===a.key&&old.S.stepN<=a.state.substep){while(old.S.stepN<a.state.substep)__dphys.tick(old.S);const state=__dphys.snapshot(old.S);for(const [x,y]of [[state.body,a.state.body],[state.hands[0],a.state.hands[0]],[state.hands[1],a.state.hands[1]],[state.light,a.state.light]].filter(Boolean)){if(!x||!y)continue;for(const k of ['support','sleeping','mode'])if(x[k]!==y[k])g5.discreteErrors.push({substep:state.substep,key:k,actual:x[k],expected:y[k]});for(const k of ['x','y','z','vx','vy','vz','yaw'])g5.maxError=Math.max(g5.maxError,Math.abs(x[k]-y[k]));}g5.comparisons++;}
    if(a.resume)g5.previous={key:a.key,S:__dphys.restore(a.event,g,a.resume,a.state)};else g5.previous=null;
    history.ingest(TFB_PROTOCOL.aftermathPoses(r,g),Date.now());g5.records.push({key:a.key,n:a.state.substep,state:a.state.state,resumeBytes:a.resume?JSON.stringify(a.resume).length:0,objects:TFB_PROTOCOL.aftermathPoses(r,g).length});g5.last=a;
   }}
  };g5.pass=pass;
 },{d,pass:process.env.ADMIN_PASSCODE||'smoor'});
 await page.waitForFunction(()=>g5.client.anchor);await page.evaluate(()=>g5.send({t:'join'}));await page.waitForFunction(()=>g5.client.life>0);await page.evaluate(()=>g5.send({t:'admin',pass:g5.pass,quiet:1}));await page.waitForFunction(()=>g5.admin);await page.evaluate(()=>g5.send({t:'a',c:'preview',k:'hound',var:'A'}));await page.waitForFunction(()=>g5.last?.state.state==='SLEEPING',{},{timeout:20000});
 const result=await page.evaluate(()=>({comparisons:g5.comparisons,maxError:g5.maxError,tolerance:TFB_MOTION.POLICY.epsilon,discreteErrors:g5.discreteErrors,records:g5.records,historyObjects:g5.history.hist.size,finalKey:g5.last.key,finalSubstep:g5.last.state.substep,finalObjects:TFB_PROTOCOL.aftermathPoses(g5.client.aftermaths.values().next().value,g5.g),glError:stageD.views[0].pass.gl.getError()}));let raw=path.join(out,'cross-runtime-raw.json'),attempt=1;while(fs.existsSync(raw))raw=path.join(out,'cross-runtime-raw-'+attempt+++'.json');fs.writeFileSync(raw,JSON.stringify(result,null,2)+'\n');assert(result.comparisons>20);assert(result.maxError<=result.tolerance);assert.deepEqual(result.discreteErrors,[]);assert.equal(result.glError,0);assert.equal(result.historyObjects,result.finalObjects.length);assert.equal(result.historyObjects,4); // default connection has no hat
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 const summary={status:'PASS',browser:browser.version(),runtime:process.version,http,errors,failed,...result,scope:'Actual HTTP modules, real browser WebSocket death records, bounded restore and forward kernel agreement within locked geometry epsilon, exact discrete support/sleep/mode agreement; retained common history. No Stage H rendering integration.'};fs.writeFileSync(path.join(out,'runtime.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary));await page.close();
 }finally{if(browser)await browser.close();await s.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
