'use strict';
const assert=require('assert'),fs=require('fs'),M=require('../../world_motion'),P=require('../../spatial_protocol'),{field}=require('../stage_f/fixture'),{server,connect,wait,sleep}=require('../stage_f/wire'),{summary,host}=require('./metrics');
process.env.ADMIN_PASSCODE=require('crypto').randomBytes(24).toString('hex');
function definition(){const d=field();for(const kind of ['hound','smiler']){d.colliderProfiles.push({...M.ENTITY_PROFILES[kind],capabilities:['walk']});for(let i=0;i<(kind==='hound'?3:5);i++)d.anchors.push({id:`anchor:${kind}-${i}`,kind:kind+'-spawn',position:{x:3500+i*600,y:kind==='hound'?300:800,z:0},yaw:0,supportId:'support:ground',spaceId:null,colliderProfileId:'profile:'+kind});}for(const k of ['anchors','colliderProfiles'])d[k].sort((a,b)=>a.id.localeCompare(b.id));return d;}
async function command(c,m){const before=c.messages.filter(x=>x.t==='ares').length;c.send({t:'a',...m});await wait(()=>c.messages.filter(x=>x.t==='ares').length>before,'admin response',20000);return c.messages.filter(x=>x.t==='ares').at(-1);}
function meter(c){const m={bytes:0,frames:0,maxFrame:0,intervals:[],last:null};c.ws.addEventListener('message',e=>{const now=performance.now();m.bytes+=Buffer.byteLength(e.data);m.frames++;m.maxFrame=Math.max(m.maxFrame,Buffer.byteLength(e.data));if(m.last!==null)m.intervals.push(now-m.last);m.last=now;});return m;}
const rss=pid=>{try{return Number(fs.readFileSync('/proc/'+pid+'/status','utf8').match(/^VmRSS:\s+(\d+)/m)?.[1])*1024;}catch{return null;}};
(async()=>{const d=definition(),s=await server(d),all=[],rows=[];try{
 const rooms=[];for(let r=0;r<3;r++){const cs=[];for(let i=0;i<(r===0?4:2);i++){const c=await connect(s,d,'stage-i-soak-'+r);await c.join();all.push(c);cs.push(c);}await cs[0].admin();rooms.push(cs);}
 const meters=all.map(meter),initial=rooms.map(cs=>({epoch:cs[0].client.world.worldEpoch,tick:cs[0].last.protocol.simTick})),memory=[],timelines=[],start=performance.now();let churn=0;
 for(let second=0;second<60;second++){
  await sleep(1000);memory.push(rss(s.child.pid));timelines.push(rooms.map(cs=>({tick:cs[0].last.protocol.simTick,cpu:cs[0].last.spatialStats.cpu,stats:cs[0].last.spatialStats,entities:cs[0].last.spatial.filter(p=>p.entityId[0]!=='p').length})));
  if(second===12){assert((await command(rooms[0][0],{c:'preview',k:'hound',var:'A'})).ok);}
  if([18,30,42].includes(second)){const old=rooms[1].pop();old.close();await sleep(100);const c=await connect(s,d,'stage-i-soak-1');await c.join();rooms[1].push(c);all.push(c);churn++;}
  for(const cs of rooms){const a=cs[0].last.spatialStats;assert(a.maxQueue<=P.LIMIT.queue&&a.maxHistory<=P.LIMIT.history&&a.maxWork<=P.LIMIT.work);assert(cs[0].history.hist.size<=256);assert([...cs[0].history.hist.values()].every(h=>h.length<=8));}
 }
 const seconds=(performance.now()-start)/1000;const final=rooms.map((cs,i)=>({room:i,players:cs.length,initial:initial[i],finalTick:cs[0].last.protocol.simTick,cpu:cs[0].last.spatialStats.cpu,stats:cs[0].last.spatialStats}));
 for(const r of final)assert(r.finalTick>r.initial.tick+3000,'sustained room tick progress');
 const disposable=rooms[2],oldEpoch=disposable[0].client.world.worldEpoch;disposable.forEach(c=>c.close());await sleep(300);const recreated=await connect(s,d,'stage-i-soak-2');all.push(recreated);await recreated.join();assert.notEqual(recreated.client.world.worldEpoch,oldEpoch);assert(recreated.last.protocol.simTick<120);recreated.close();
 rows.push({workload:'three real rooms / eight initial clients / director + death + reconnect churn',seconds,churn,final,timelines,rssBytes:summary(memory.filter(Number.isFinite)),rssStart:memory[0],rssEnd:memory.at(-1),network:meters.map(m=>({bytes:m.bytes,bytesPerSecond:m.bytes/seconds,frames:m.frames,maxFrame:m.maxFrame,arrivalMs:summary(m.intervals)})),roomRecreation:{oldEpoch,newEpoch:recreated.client.world.worldEpoch,oldStateExcluded:true},classification:'PASS / BOUNDED 60 SECOND MEASUREMENT; not long-term leak or capacity certification'});
 for(const c of all)c.close();await sleep(300);
 // Separate actual admin ceiling, measured with live brains after frozen setup.
 const c=await connect(s,d,'stage-i-admin-ceiling');all.push(c);await c.join();await c.admin();assert((await command(c,{c:'god',id:c.hi.id})).ok);assert((await command(c,{c:'freeze',on:true})).ok);
 await sleep(200);const counts={hound:c.last.spatial.filter(p=>p.entityId[0]==='h').length,smiler:c.last.spatial.filter(p=>p.entityId[0]==='m').length};
 for(const kind of ['hound','smiler'])for(let i=counts[kind];i<64;i++)assert((await command(c,{c:'spatial-entity',kind,pose:{x:2000+(i%16)*280,y:150+Math.floor(i/16)*250,z:kind==='hound'?0:200,support:kind==='hound'?'support:ground':'support:upper'}})).ok);
 await wait(()=>c.last.spatial.filter(p=>p.entityId[0]!=='p').length===128,'full admin ceiling',20000);
 const rejected=await command(c,{c:'spatial-entity',kind:'hound',pose:{x:500,y:500,z:0,support:'support:ground'}});assert(!rejected.ok&&rejected.msg==='ENTITY LIMIT');
 const met=meter(c);assert((await command(c,{c:'freeze',on:false})).ok);const started=performance.now(),tick=c.last.protocol.simTick;await sleep(10000);const stats=c.last.spatialStats;assert(c.last.protocol.simTick>tick+300);assert(stats.maxQueue<=90&&stats.maxWork<=15);rows.push({workload:'64 Hounds + 64 Smilers active real server',seconds:(performance.now()-started)/1000,entities:128,frozenDuringMeasurement:false,cpu:stats.cpu,advancedTicks:c.last.protocol.simTick-tick,serverRssBytes:rss(s.child.pid),bytesPerSecond:met.bytes/((performance.now()-started)/1000),maxFrameBytes:met.maxFrame,arrivalMs:summary(met.intervals),capReject:rejected,classification:'PASS / BOUNDED STRESS MEASUREMENT; not a normal-room threshold'});
 const result={status:'PASS',host:host(),world:require('../../world_geometry').compile(d).identity,seed:'production server RNG; no deterministic trajectory claim',rows};fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){fs.writeFileSync(process.argv[2]+'.failure.json',JSON.stringify({status:'FAIL',error:String(e),stack:e.stack,rows,last:all.slice(0,3).map(c=>c.last),server:s.log},null,2));throw e;}finally{all.forEach(c=>c.close());await s.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
