'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Module=require('module');
const {world,box,fixture,G:plain,M}=require('../stage_c/helpers'),{summary,host}=require('./metrics');
// Observe real internal loop/candidate counters without altering query decisions.
let src=fs.readFileSync(path.resolve(__dirname,'../../world_geometry.js'),'utf8');
const edits=[['function compileSpatial(definition){','function compileSpatial(definition){ const measured={candidateQueries:0,candidates:0,maxCandidates:0,advanceIterations:0};'],['return [...set].sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);','measured.candidateQueries++; measured.candidates+=set.size; measured.maxCandidates=Math.max(measured.maxCandidates,set.size); return [...set].sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);'],['for(let i=0;i<NUM.advanceIterations;i++){','for(let i=0;i<NUM.advanceIterations;i++){ measured.advanceIterations++;'],['clearance,supports,sweep,raycast,continuousSupport,contact,traceSupportMotion,propagateSound,','measured,clearance,supports,sweep,raycast,continuousSupport,contact,traceSupportMotion,propagateSound,']];
for(const [a,b]of edits){assert.equal(src.split(a).length,2,'unique instrumentation anchor');src=src.replace(a,b);}
const filename=path.resolve(__dirname,'../../world_geometry.js'),mod=new Module(filename,module);mod.filename=filename;mod.paths=module.paths;mod._compile(src,filename);const G=mod.exports,rows=[];
for(const count of [4,16,64]){
 const d=world(Array.from({length:count},(_,i)=>box(String(i).padStart(3,'0'),0,0,400,400,i*80-12,i*80)));d.bounds.max.z=count*80+200;
 const begin=performance.now(),g=G.compile(d),compileMs=performance.now()-begin,control=plain.compile(d),times=[],hits=[];
 for(let n=0;n<500;n++){const pos={x:100+n%40,y:160,z:count*80+100},delta={x:0,y:0,z:-(count*80+150)},start=performance.now();const hit=g.sweep(M.PROFILES.stand,pos,delta);times.push(performance.now()-start);assert.equal(hit.primitiveId,'solid:'+String(count-1).padStart(3,'0'));assert(!hit.diagnostic);if(n<20)assert.deepEqual(hit,control.sweep(M.PROFILES.stand,pos,delta));hits.push(hit.t);}
 rows.push({workload:'stacked same-XY dense swept Z range',solids:count,queries:500,compileMs,sweepMs:summary(times),queryCounters:{...g.measured},candidatesPerQuery:g.measured.candidates/g.measured.candidateQueries,fallbacks:0,index:g.indexInfo,world:g.identity});
 const before={...g.measured},local=[];for(let n=0;n<500;n++){const p={x:100+n%40,y:160,z:0},t=performance.now();assert.equal(g.supports(M.PROFILES.stand,p,[-.1,.1])[0].id,'support:000');assert(g.clearance(M.PROFILES.stand,p).fits);local.push(performance.now()-t);}const queries=g.measured.candidateQueries-before.candidateQueries,candidates=g.measured.candidates-before.candidates;assert(candidates<=queries);rows.push({workload:'local Z-filtered support and clearance below stacked floors',solids:count,queries,candidates,candidatesPerQuery:candidates/queries,pairedQueryMs:summary(local)});
}
const g=G.compile(fixture),times=[],motion=M.create(g),starts=[{x:600,y:148,z:0},{x:368,y:85,z:0},{x:880,y:660,z:120},{x:140,y:770,z:0}];let diagnostics=0;
for(let i=0;i<starts.length;i++){const b=motion.initialize({...starts[i]},i===3?'crawl':'stand');for(let t=0;t<240;t++){b.vx=i===1||i===2?0:100;b.vy=i===1||i===2?100:0;const start=performance.now();motion.step(b);times.push(performance.now()-start);assert(g.clearance(b.shape,b).fits);diagnostics+=b.diagnostics.length;}}
assert.equal(diagnostics,0);rows.push({workload:'real ramp stair drop crawl motion',ticks:960,motionTickMs:summary(times),queryCounters:{...g.measured},fallbacks:diagnostics,world:g.identity});
const result={status:'PASS',host:host(),seed:0,rows,classification:'PASS / BOUNDED MEASUREMENT',instrumentation:'Counters only; first 20 sweeps per density compared exactly with uninstrumented production module'};fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2));console.log(JSON.stringify(result));
